config/routes.rb
Rails.application.routes.draw do
  # This line mounts Spree's routes at the root of your application.
  # This means, any requests to URLs such as /products, will go to
  # Spree::ProductsController.
  # If you would like to change where this engine is mounted, simply change the
  # :at option to something different.
  #
  # We ask that you don't use the :as option here, as Spree relies on it being
  # the default of "spree".
  mount Spree::Core::Engine, at: '/'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  Spree::Core::Engine.add_routes do
    ##
    # Admins

    namespace :admin, path: Spree.admin_path do

      match 'dashboard', to: 'base#dashboard', as: :dashboard, via: [:get]
      match 'stats', to: 'base#stats', as: :stats, via: [:get]
      match 'sellers', to: 'users#sellers', as: :sellers, via: [:get]
      match 'all_sellers', to: 'users#all_sellers', as: :all_sellers, via: [:get]
      match 'buyers', to: 'users#buyers', as: :buyers, via: [:get]
      match 'critical_response', to: 'stores#critical_response', as: :critical_response, via: [:get, :put, :post]
      match 'update_options', to: 'stores#update_options', as: :update_options, via: [:put, :post]
      match 'soft_delete_user/:id', to: 'users#soft_delete', as: :soft_delete_user, via: [:put, :post]
      match 'restore/:id', to: 'users#restore', as: :restore_user, via: [:put, :post]
      match 'limit_user/:id', to: 'users#limit_user', as: :limit_user, via: [:put, :post]
      match 'remove_limit/:id', to: 'users#remove_limit', as: :remove_limit, via: [:put, :post]
      match 'niir/:version', to: 'record_reviews#products', as: :niir_version, via: [:get]
      match 'niir', to: 'record_reviews#products', as: :niir, via: [:get]
      match 'record_reviews/mark_reviewed', to: 'record_reviews#mark_reviewed', as: 'mark_record_reviewed', via: [:get, :put]

      match 'remove_user_list_user/:id', to: 'user_lists#remove_user', as: 'remove_user_list_user', via: [:put, :post, :delete]
      match 'remove_product_list_product/:id', to: 'product_lists#remove_product', as: 'remove_product_list_product', via: [:put, :post, :delete]
      resources :user_lists
      resources :record_reviews
      resources :product_lists

      # Product manager
      match '/product_manager/preview_takedown' => 'product_manager#preview_takedown', as: 'preview_takedown', via: [:put, :post, :delete]
      match '/product_manager/takedown' => 'product_manager#takedown', as: 'takedown', via: [:put, :post, :delete]
      get '/product_manager' => 'product_manager#index', as: 'product_manager'

      # Products
      match '/wanted_products', to: 'stores#find_and_list_items', as: 'wanted_products', via: [:get]
      match '/listing_policy', to: 'stores#update_listing_policy', as: 'update_item_listing_policy', via: [:put, :post]
      match '/listing_policy', to: 'stores#listing_policy', as: 'item_listing_policy', via: [:get]
      match '/find_and_list_items', to: 'stores#find_and_list_items', as: 'find_and_list_items', via: [:get]
      match '/products/:id/list_same_item' => 'products#list_same_item', as: 'list_same_item', via: [:get]
      match '/products/:id/list_variants' => 'products#list_variants', as: 'list_variants', via: [:put, :post]

      match 'other_listings', to: 'products#adopted', as: 'other_listings', via: [:get]
      match 'products_adopted', to: 'products#adopted', as: 'products_adopted', via: [:get]
      match '/products/top_selling', to: 'products#top_selling', as: 'products_top_selling', via: [:get]
      match 'products/toggle_selling_taxon', to: 'products#toggle_selling_taxon', as: 'toggle_selling_taxon', via: [:get, :put, :post]
      match 'products/:id/erase', to: 'products#erase', as: 'erase_product', via: [:delete]
      match '/products/:id/debug' => 'products#show_debug', as: 'product_debug', via: [:get, :put, :post]

      match 'products/:product_id/images/:id/mark_as_main', to: 'images#mark_as_main', as: 'mark_image_as_main', via: [:get, :put, :post]
      match 'products/:product_id/upload_images/:id', to: 'images#delete_image', as: 'product_delete_image', via: [:delete]
      match 'products/:product_id/upload_images', to: 'images#upload_images', as: 'product_upload_images', via: [:put, :post]
      match 'products_batch_update' => 'products#batch_update', as: 'batch_update_products', via: [:put, :post]


      ##
      # Seller
      match '/orders/:id/preview_invoice_email' => 'orders#preview_invoice_email', as:'order_preview_invoice_email', via: [:get]

      # Orders
      match '/orders/:id/update_messages' => 'orders#update_messages', via: [:put, :post], as: 'order_update_messages'
      match '/orders/:id' => 'orders#show', as:'order', via:[:get]
      match '/sales/:state' => 'orders#sales', as:'sales_in_state', via: [:get]
      match '/sales' => 'orders#sales', as:'sales', via: [:get]
      match '/msales' => 'orders#mobile_sales', as:'mobile_sales', via: [:get]

      # Store
      match '/payment_methods_and_retail_stores' => 'store_payment_methods#save_payment_methods_and_retail_stores', as:'payment_methods_and_retail_stores', via: [:get, :put, :post]
      match '/store_payment_methods/toggle' => 'store_payment_methods#toggle', as: 'toggle_store_payment_method', via: [:get, :put, :post]
      resources :store_payment_methods, only:[:index, :show, :update]
      get '/fill_your_shop' => 'stores#fill_your_shop', as: 'fill_your_shop'

      # Imports
      match '/scraper_page_imports/select(.:format)' => 'scraper_page_imports#select', as: 'select_scraper_page_imports', via: [:post, :put]
      match '/products/imported' => 'scraper_page_imports#products', as: 'imported_products', via: [:get]
      match 'scraper_page_imports' => 'scraper_page_imports#products', as: 'page_product_imports', via: [:get]

    end


    # Users
    get Spree.admin_path => 'admin/base#home', as: :admin_default

    get '/account' => 'users#account', as: 'account'
    match '/onboarding/:passcode/password' => 'users#onboarding_change_password', as: 'onboarding_change_password', via: [:get, :put, :post, :patch]
    get '/onboarding/:passcode' => 'users#onboarding', as: 'user_onboarding'

    get '/users/info' => 'admin/users#show', as: 'users_info'
    get '/users/:username' => 'home#not_found', as: 'users_detail'

    devise_scope :spree_user do
      match '/admin/sign_in_as/:id' => 'user_sessions#sign_in_as', as:'admin_sign_in_as', via: [:get, :put, :post]
    end

    ##
    # Products
    match '/products_s' => 'products#index', as: 's_products', via: [:get, :put, :post]
    match '/products_m' => 'products#index', as: 'm_products', via: [:get, :put, :post]
    match '/products_sd' => 'products#index', as: 'sd_products', via: [:get, :put, :post]
    match '/products_md' => 'products#index', as: 'md_products', via: [:get, :put, :post]
    match '/products_l' => 'products#index', as: 'l_products', via: [:get]
    match '/products_c' => 'products#index', as: 'c_products', via: [:get]
    match '/products/:id/exists_in_search' => 'products#exists_in_search', as: 'product_exists_in_search', via: [:get, :put, :post]
    match '/products/:id/related' => 'products#related_products', as: 'related_products', via: [:get, :put, :post]
    match '/related_option_types/:record_type/:record_id' => 'api/option_types#related', as: :related_option_types, via: [:get, :put, :post]
    match '/variants/:id/data' => 'products#variant_data', as: 'product_variant_data', via: [:get, :put, :post]
    match '/option_types/load' => 'api/option_types#load', as: :load_option_types, via: [:get, :put, :post]
    match '/admin/taxons/:id/related_option_types', to: 'admin/taxons#related_option_types', as: :taxon_related_option_types, via: [:get]

    #get '/search', to: 'products#index', as: 'search_by_id'
    #get '/search', to: 'searches#show', as: 'search_by_id'

    ##
    # Buyer
    match '/add_item_to_cart' => 'api/v2/storefront/cart#add_item', via: [:put, :post], as: 'populate_orders'
    match '/select_variant' => 'api/v2/storefront/cart#select_variant', via: [:put, :post], as: 'select_variant'
    match '/orders/:id/help' => 'orders#help', via: [:get], as: 'order_help'
    match '/orders/:id/upload_image' => 'orders#upload_image', via: [:patch, :put, :post], as: 'order_upload_image'
    match '/orders/:id/messages/:message_id' => 'orders#show_message', via: [:get], as: 'order_show_message'
    match '/orders/:id/messages' => 'orders#create_message', via: [:get, :put, :post], as: 'order_create_message'
    match '/orders' => 'orders#index', via: [:get], as: 'orders'
    patch "/orders/:id/update_channel", to: "orders#update_channel", as: :update_order_channel


    # Sellers
    get '/payment_methods_provided' => 'store_payment_methods#payment_methods_provided', as: 'payment_methods_provided'
    get '/payment_method_accounts' => 'store_payment_methods#accounts', as: 'payment_method_accounts'

    ##
    # Orders
    get '/recent_sales(.:format)' => 'orders#recent_sales',  as: 'recent_sales'

    # iOffer Landing
    match '/other' => 'home#other_site_accounts', via: [:get], as:'other'
    match '/contact_info' => 'home#payment_info', via: [:get], as: 'contact_info'
    match '/seller_contact_info' => 'home#payment_info', via: [:get], as: 'seller_contact_info'
    match '/payment_options' => 'home#payment_options', via: [:get], as: 'payment_options'
    match '/seller_obligations' => 'home#seller_obligations', via: [:get], as: 'seller_obligations'

    # iOffer Static Pages
    match '/privacy_policy' => 'base#privacy_policy', via: [:get], as:'privacy'
    match '/terms' => 'base#terms_of_use', via: [:get], as:'terms'

    get '/u/:code', to: 'item_reviews#show', as: :item_review
    get '/u/:code/purchases', to: 'item_reviews#purchases', as: :purchases_item_review


    # Must be here for spree home to access path urls
    namespace :ioffer, path: '/' do

app/models/ioffer/user.rb
class Ioffer::User < Spree::Base

  include Ioffer::EncryptionHelper

  devise :database_authenticatable, :recoverable

  END_OF_IMPORTED_USERS = Time.local(2020, 5, 8)

  USERNAME_REGEXP = /\A[\w\.\-_]+\Z/
  EMAIL_REGEXP = /\A[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}\Z/i
  validates :email, :presence => true, :format => EMAIL_REGEXP
  validates_uniqueness_of :email, message: I18n.t('errors.user.email_taken')
  validates :username, format: USERNAME_REGEXP
  validates_uniqueness_of :username, message: I18n.t('errors.user.username_taken')
  validates :password, confirmation: true

  has_many :user_payment_methods, dependent: :delete_all
  has_many :payment_methods, through: :user_payment_methods

  has_many :user_categories, dependent: :delete_all
  has_many :categories, through: :user_categories

  has_many :user_brands, dependent: :delete_all
  has_many :brands, through: :user_brands

  has_many :other_site_accounts, dependent: :delete_all, class_name:'Retail::OtherSiteAccount'

  belongs_to :spree_user, foreign_key:'user_id', class_name:'Spree::User'

  scope :with_related_spree_user, -> { joins(:spree_user).where("#{Spree::User.table_name}.id IS NOT NULL") }
  scope :no_email_sent, -> { where('last_email_at IS NULL') }
  scope :should_get_email, -> { where('last_email_at IS NULL AND email_trial_count < 3') }
  scope :not_claimed, -> { where('reset_password_token IS NOT NULL') }
  scope :claimed, -> { where('reset_password_token IS NULL') }

  self.whitelisted_ransackable_associations = %w[spree_user other_site_accounts user_payment_methods payment_methods]
  self.whitelisted_ransackable_attributes = %w[username email location gms ip]

  @@encryption_key = nil

  before_save :encrypt_password
  before_validation :normalize_attributes
  after_create :convert!

  PERMITTED = [:username, :email, :password, :password_confirmation, :reset_password_token, :other_site_account_id]

  attr_accessor :password, :password_confirmation
  attr_writer :login

  def login
    @login || self.username || self.email
  end

  def positive_ratio
    positive.to_f / (positive + negative)
  end

  def claimed?
    username.present? && reset_password_token.blank?
  end

  def legacy?
    created_at < END_OF_IMPORTED_USERS
  end

  def sign_up_time
    created_at && created_at > END_OF_IMPORTED_USERS ? created_at : nil
  end

  ###############################
  # Actions

  ##
  # The public call to only regenerate reset_password_token and save w/o sending instructions.
  def reset_password_token!
    set_reset_password_token
  end


  ##
  # Find or create Retail::Store, connected Spree::User, and then Spree::Store, and then 
  # payment_methods, categories.
  # This calls the sequence of convert_to_retail_store!, convert_to_spree_user!, 
  # convert_payment_methods!, convert_categories! at last.
  # @return [Spree::User]
  def convert!
    rstore = convert_to_retail_store!
    
    rstore_conv = rstore.spree_user_migration

    spree_user = nil
    Spree::User.transaction do
      spree_user = rstore_conv.try(:spree_user) || convert_to_spree_user!
      rstore_conv = Retail::StoreToSpreeUser.find_or_create_by(retail_store_id: rstore.id, spree_user_id: spree_user.id)

      spree_user.store ||= spree_user.create_store!
    end

    convert_payment_methods!(spree_user) if spree_user

    convert_categories!(spree_user) if spree_user

    spree_user
  end

  #####################
  # Individual conversion methods

  ##
  # @return [Retail::Store]
  def convert_to_retail_store!
    ioffer = Retail::Site.find_by_name('ioffer')
    rstore = Retail::Store.find_or_initialize_by(retail_site_id: ioffer.id, retail_site_store_id: username) 
    rstore.store_url ||= "https://www.ioffer.com/stores/#{username}"
    rstore.name ||= username
    rstore.save

    rstore
  end

  def convert_other_site_accounts!(spree_user = nil)
    spree_user ||= convert_to_spree_user!
    other_site_accounts.collect do|other_site_account|
      site = Retail::Site.find_by_name(other_site_account.site_name)
      next if site.nil?
      rstore = Retail::Store.find_or_initialize_by(retail_site_id: site.id, retail_site_store_id: other_site_account.account_id) 
      rstore.name ||= other_site_account
      rstore.save
      rstore
    end
  end

  ADDRESS_REGEXP = /(?<zipcode>[\w\-]+),\s*(?<country>[a-z\s]+)\Z/i
  ##
  # @return [Spree::User] # 
  def convert_to_spree_user!
    user = username.present? ? Spree::User.find_or_initialize_by(username: username) : 
      Spree::User.find_or_initialize_by(email: email)
    user.login = username
    user.email = email
    user.display_name = name.try(:strip)
    begin
      user.password ||= self.class.decrypt(encrypted_password) if encrypted_password.present?
    rescue OpenSSL::Cipher::CipherError, IOError
      user.password ||= 'usertransfer00'
    end
    if address
      country_record = nil
      if (address_m = address.match(ADDRESS_REGEXP) )
        user.country = address_m[:country].strip
        country_record = ::Spree::Country.where(name: user.country).first
        user.country_code = country_record.try(:ios3)
        user.zipcode = address_m[:zipcode]
      end
    end
    user.save if user.new_record?
    self.spree_user = user
    self.update(user_id: user.id) if user.id

    user 
  end

  ##
  # @spree_user [Spree::User]
  def convert_categories!(spree_user = nil, erase_old = true)
    spree_user ||= convert_to_spree_user!
    ::Spree::UserSellingTaxon.where(user_id: spree_user.id).delete_all if erase_old && categories.present?
    categories.each do|ioffer_cat|
      ioffer_cat.category_to_taxons.each do|ct|
        selling = ::Spree::UserSellingTaxon.find_or_create_by(user_id: spree_user.id, taxon_id: ct.taxon_id)
      end
    end
  end

  ##
  # @spree_user [Spree::User]
  # @erase_all [Boolean] If true, this would entirely erase all Spree::StorePaymentMethod for the 
  #   user, which also includes the account parameters.  Otherwise, would only delete missing ones.
  def convert_payment_methods!(spree_user = nil, erase_all = false)
    return [] if payment_methods.blank?

    spree_user ||= convert_to_spree_user!
    
    # Erase equivalent Spree::PaymentMethod
    spree_pm_h = {}
    payment_methods.collect do|ioffer_pm|
      pm = ioffer_pm.same_spree_payment_method
      spree_pm_h[ioffer_pm.id] = pm.id
    end

    query = Spree::StorePaymentMethod.where(store_id: spree_user.fetch_store.id)
    query = query.where('payment_method_id NOT IN (?)', spree_pm_h.values) if !erase_all && spree_pm_h.size > 0
    query.delete_all

    payment_methods.collect do|ioffer_pm|
      if (pm_id = spree_pm_h[ioffer_pm.id] )
        Spree::StorePaymentMethod.find_or_create_by(store_id: spree_user.fetch_store.id, payment_method_id: pm_id)
      end
    end
  end

  private

  def encrypt_password
    if password
      self.encrypted_password = self.class.encrypt(password)
    end
  end

  def normalize_attributes
    self.address.gsub!(/(<\w+[^>]*\/?>)/, "\n") if address.present?
    self.name = name.titleize if name.present?
    if username
      self.username.strip! 
      unless username.blank? || username =~ USERNAME_REGEXP
        self.errors.add(:username, :invalid, message: I18n.t('user.provide_a_valid_username'))
      end
    end
  end

end

app/models/user/order_broken_tracking_number.rb
module User
  class OrderBrokenTrackingNumber < OrderNeedTrackingNumber
    def self.level
      1300
    end

    def recipient_must_respond?
      true
    end
  end
end

app/models/user/order_corrected_tracking_number.rb
module User
  class OrderCorrectedTrackingNumber < OrderProvidedTrackingNumber
    
  end
end

app/models/user/order_other_question.rb
module User
  class OrderOtherQuestion < OrderMessage
    def show_only_to_recipient?
      true
    end
  end
end

app/models/user/order_payment_confirmed.rb
module User
  class OrderPaymentConfirmed < OrderMessage

  end
end

app/views/spree/admin/users/_seller_admin_row.html.haml
:ruby
  # CSS rules moved to app/assets/stylesheets/spree/record_reviews.css.scss for only 1 time load
  #
  # Required locals:
  #   either user [Spree::User] or variant [Spree::Variant]
  # Optional locals:
  #   show_admin_actions [Boolean]
  #   paypal [Spree::PaymentMethod] Paypal; if nil, would fetch locally
  show_admin_actions = true unless defined?(show_admin_actions)
  paypal = Spree::PaymentMethod.paypal unless defined?(paypal) && paypal
  if defined?(variant) && variant.is_a?(Spree::Variant)
    user = variant.user
    user.variant = variant
  end
  paypal_spm = user.store&.paypal_store_payment_method
  paypal_account_id = paypal_spm&.account_id_in_parameters
  paypal_store_pm = user.store ? user.store.store_payment_methods.find{|spm| spm.payment_method_id == paypal.id } : nil
  is_bad_seller = ( (user.variant_adoption || user.variant)&.seller_based_sort_rank == 0)
  @has_hidden_seller_rows = true if is_bad_seller
%div(class="seller-row row #{'bad-seller-row ' if is_bad_seller}#{user.has_role_of_name?('hp_seller') ? 'border-highlight' : 'border-top'} pb-1 pt-1" data-user-id="#{user.id}")
  %div(class="col-#{show_admin_actions ? '9 col-md-10' : '12'}")
    .row
      .col-2.col-xs-auto
        %div.img-container
          = country_flag_icon_of(user, { class:'' }) do
            - if paypal_store_pm
              = image_tag(asset_path('payment_methods/mini_avatar/paypal.svg'), class:'mini-avatar overlay-img white-bg', title:'Paypal')
      .col.col-6.col-xs-auto
        %div
          %label.text-secondary Email &nbsp;
          = link_to user.email, admin_users_path(q:{ email_eq: user.email.strip}), class:'mr-3'
          = link_to main_app.new_user_message_path(user_message:{ recipient_user_id: user.id }, title:'Send Message to') do
            %i(class="mr-2 icon icon-comment")
        %div
          %label.text-secondary PayPal &nbsp;
          - if paypal_spm
            = link_to paypal_account_id, admin_all_sellers_path(q:{ payment_method_id_eq: paypal_spm.payment_method_id, store_store_payment_methods_account_parameters_cont: paypal_account_id })
          - else
            = paypal_account_id
          %span(class='ml-3 mr-3') &nbsp;
        - if paypal_store_pm && paypal_store_pm.instruction.present?
          %div
            - if true # show_admin_actions # even product detail page wants to edit
              = form_for([:admin, paypal_store_pm], remote: true ) do|store_pm_form|
                = store_pm_form.text_area :instruction, class:'border-1 min-w-75 min-h-100 editable-field', disabled: true
                &nbsp;&nbsp;
                = link_to "##{paypal_store_pm.id}", class:'editable-edit' do
                  %small Edit
                = link_to "##{paypal_store_pm.id}", class:'editable-cancel-edit d-none', data:{ 'store-payment-method-id' => store_pm_form.object.id } do
                  %span(class='icon icon-remove')
                = store_pm_form.button type:'submit', class:'editable-update d-none border-0 bg-transparent' do
                  %span(class='icon icon-floppy-disk')
            - else
              = paypal_store_pm.instruction
      .col.col-xs-auto.text-right
        %div
          %span(title="ID #{ user.id } seller_rank #{user.seller_rank}#{ ' From iOffer' if user.ioffer_user }" data-toggle='tooltip')= link_to(user.real_username || '---', admin_user_path(user))
          &nbsp;(
          %span(class='' title='Positive' data-toggle='tooltip')= user.ioffer_user&.positive
          = ' / '
          %span(class='text-danger' title='Negative' data-toggle='tooltip')= user.ioffer_user&.negative
          &nbsp;)
          - seller_status_icons(user).each do|icon|
            = icon.html_safe
        .ml-1.mt-1
          - months_of_reg = ((Time.now - user.created_at) / 1.month).round
          &nbsp;
          %span(class="absolute-right mr-3 one-quarter-opacity")
            %i(data-feather="moon")
          %strong.absolute-right.mr-3(title="Count of Months Registered")= months_of_reg
        - if (vprices = (user.variant_adoption || user.variant)&.prices )
          %br
          %strong= display_price(user.variant_adoption || user.variant)
    - prods = curated_products(user)
    .row
      .col-10.col-sm-8
        - match_to_others_icons(user).each do|el|
          = el.html_safe
        %span.ml-1 &nbsp;
        - if user.last_active_at
          %span(title="Last active time: #{ user.last_active_at&.to_s(:db) }") Active #{time_ago_in_words(user.last_active_at) } ago
        - else
          %span.text-secondary(title='Inactive / No Login') ???
        -# %strong(title='Current Sign In IP')= user.current_sign_in_ip ? link_to(user.current_sign_in_ip, admin_users_path(q:{ current_sign_in_ip_eq: user.current_sign_in_ip })) : ''
        .seller-products.mt-2
          - prods.each do |product|
            = link_to product_path(product), target: '_blank' do
              - image = default_image_for_product_or_variant(product)
              = image_tag cdn_image_url(image, :product), class: 'image-style mr-1'

          = link_to "#{user.count_of_products_created || user.products.count} Created", admin_products_path(q:{ user_id_eq: user.id })
      .col-2.col-sm-4.text-right
        = link_to "#{user.adopted_products_count} Adopted", admin_products_adopted_path(variant_adoptions_user_id_eq: user.id )
  - if show_admin_actions
    .col-3.col-md-2.text-right
      = link_to_edit user, url: edit_admin_user_path(user), no_text: true if can?(:edit, user)
      = link_to_delete user, url: admin_user_path(user), no_text: true if can?(:delete, user)

app/views/spree/admin/users/_user_page_actions.html.erb
<% content_for :page_actions do %>
  <% if spree_current_user.try(:admin?) %>
  <%= button_link_to Spree.t('admin.users.sign_in_as'), admin_sign_in_as_path(id: @user.id), title: @user.login || @user.email, method:'put', data:{ disable_with:'Signing In ...'}, class: "btn-success", icon: 'user' %>
  <% end # admin %>
<% end %>

app/views/spree/admin/users/_user_table_row.html.erb
<%
  # General user info in table row, compared to _seller_row that's has extensive seller info.
  # Required locals:
  #   user [Spree::User]
  # Optional locals:
  #   paypal [Spree::PaymentMethod] Paypal; if nil, would fetch locally
  paypal = Spree::PaymentMethod.paypal unless defined?(paypal) && paypal
  paypal_account_id = user.store ? (user.store.account_parameters_of(paypal.id) || {})['account_id']  : nil
  paypal_store_pm = user.store ? user.store.store_payment_methods.find{|spm| spm.payment_method_id == paypal.id } : nil
  last_sign_in_log = user.request_logs.find_all{|log| log.group_name == 'sign_in' }.last
-%>
<tr id="<%= spree_dom_id user %>" data-hook="admin_users_index_rows">
  <td><span title="Joined at <%= user.created_at.to_s(:db) %>"></span><%= user.id %></span></td>
  <td>
    <span title="<%= 'From iOffer' if user.ioffer_user -%>"><%= link_to(user.real_username, admin_user_path(user)) %></span>
  </td>
  <td class='user_email'><%=link_to user.email, edit_admin_user_path(user) %></td>
  <td>
    <% if paypal_account_id && paypal_store_pm -%>
      <%= link_to admin_users_path(q:{ email_eq: paypal_account_id}) do -%>
        <%= image_tag(asset_path('payment_methods/mini_avatar/paypal.svg'), class:'mini-avatar white-bg', title: paypal_account_id) %>
      <% end if paypal_store_pm -%>
    <% end -%>
  </td>
  <td class="text-right"><%= short_display_of_time(user.request_logs.last&.created_at, 'data-toggle'=>'tooltip') %></td>
  <td class="text-right"><%= short_display_of_time(user.last_active_at, 'data-toggle'=>'tooltip') %></td>
  <td><span data-toggle="tooltip" title="<%= last_sign_in_log&.location_combined -%>"><%= last_sign_in_log&.country -%></span></td>
  <td class="text-right"><%= link_to user.count_of_products_created || products_count_for(user), admin_products_path(q:(params[:q] || {}).merge({ user_id_eq: user.id}) ) -%></td>
  <td class="text-right"><%= link_to user.count_of_products_adopted || products_adopted_count_for(user), admin_products_adopted_path(variant_adoptions_user_id_eq: user.id ) -%></td>
  <td data-hook="admin_users_index_row_actions" class="actions actions-2 text-right">
    <% if @user_list -%>
      <%= link_to admin_remove_user_list_user_path(id: @user_list.id, user_id: user.id, selector:"##{spree_dom_id(user)}"), method:'delete', remote: true, class:'btn btn-danger btn-sm delete-resource icon-link with-tip action-delete', title:'Remove from list' do -%>
        <span class='icon icon-delete'></span>
      <% end -%>
    <% else -%>
      <%= link_to_edit user, url: edit_admin_user_path(user), no_text: true if can?(:edit, user) %>
      <%= link_to_delete user, url: admin_user_path(user), no_text: true if can?(:delete, user) %>
    <% end -%>
  </td>
</tr>