config/routes.rb
      get '/product_manager' => 'product_manager#index', as: 'product_manager'

      # Products
      match '/wanted_products', to: 'stores#find_and_list_items', as: 'wanted_products', via: [:get]
      match '/listing_policy', to: 'stores#update_listing_policy', as: 'update_item_listing_policy', via: [:put, :post]
      match '/listing_policy', to: 'stores#listing_policy', as: 'item_listing_policy', via: [:get]
      match '/find_and_list_items', to: 'stores#find_and_list_items', as: 'find_and_list_items', via: [:get]
      match '/products/:id/list_same_item' => 'products#list_same_item', as: 'list_same_item', via: [:get]
      match '/products/:id/list_variants' => 'products#list_variants', as: 'list_variants', via: [:put, :post]

      match 'other_listings', to: 'products#adopted', as: 'other_listings', via: [:get]
      match 'products_adopted', to: 'products#adopted', as: 'products_adopted', via: [:get]
      match '/products/top_selling', to: 'products#top_selling', as: 'products_top_selling', via: [:get]
      match 'products/toggle_selling_taxon', to: 'products#toggle_selling_taxon', as: 'toggle_selling_taxon', via: [:get, :put, :post]
      match 'products/:id/erase', to: 'products#erase', as: 'erase_product', via: [:delete]
      match '/products/:id/debug' => 'products#show_debug', as: 'product_debug', via: [:get, :put, :post]

      match 'products/:product_id/images/:id/mark_as_main', to: 'images#mark_as_main', as: 'mark_image_as_main', via: [:get, :put, :post]
      match 'products/:product_id/upload_images/:id', to: 'images#delete_image', as: 'product_delete_image', via: [:delete]
      match 'products/:product_id/upload_images', to: 'images#upload_images', as: 'product_upload_images', via: [:put, :post]
      match 'products_batch_update' => 'products#batch_update', as: 'batch_update_products', via: [:put, :post]


      ##
      # Seller
      match '/orders/:id/preview_invoice_email' => 'orders#preview_invoice_email', as:'order_preview_invoice_email', via: [:get]

      # Orders
      match '/orders/:id/update_messages' => 'orders#update_messages', via: [:put, :post], as: 'order_update_messages'
      match '/orders/:id' => 'orders#show', as:'order', via:[:get]
      match '/sales/:state' => 'orders#sales', as:'sales_in_state', via: [:get]
      match '/sales' => 'orders#sales', as:'sales', via: [:get]
      match '/msales' => 'orders#mobile_sales', as:'mobile_sales', via: [:get]

      # Store
      match '/payment_methods_and_retail_stores' => 'store_payment_methods#save_payment_methods_and_retail_stores', as:'payment_methods_and_retail_stores', via: [:get, :put, :post]
      match '/store_payment_methods/toggle' => 'store_payment_methods#toggle', as: 'toggle_store_payment_method', via: [:get, :put, :post]
      resources :store_payment_methods, only:[:index, :show, :update]
      get '/fill_your_shop' => 'stores#fill_your_shop', as: 'fill_your_shop'

      # Imports
      match '/scraper_page_imports/select(.:format)' => 'scraper_page_imports#select', as: 'select_scraper_page_imports', via: [:post, :put]
      match '/products/imported' => 'scraper_page_imports#products', as: 'imported_products', via: [:get]
      match 'scraper_page_imports' => 'scraper_page_imports#products', as: 'page_product_imports', via: [:get]

    end


    # Users
    get Spree.admin_path => 'admin/base#home', as: :admin_default

    get '/account' => 'users#account', as: 'account'
    match '/onboarding/:passcode/password' => 'users#onboarding_change_password', as: 'onboarding_change_password', via: [:get, :put, :post, :patch]
    get '/onboarding/:passcode' => 'users#onboarding', as: 'user_onboarding'

    get '/users/info' => 'admin/users#show', as: 'users_info'
    get '/users/:username' => 'home#not_found', as: 'users_detail'

    devise_scope :spree_user do
      match '/admin/sign_in_as/:id' => 'user_sessions#sign_in_as', as:'admin_sign_in_as', via: [:get, :put, :post]
    end

    ##
    # Products
    match '/products_s' => 'products#index', as: 's_products', via: [:get, :put, :post]
    match '/products_m' => 'products#index', as: 'm_products', via: [:get, :put, :post]
    match '/products_sd' => 'products#index', as: 'sd_products', via: [:get, :put, :post]
    match '/products_md' => 'products#index', as: 'md_products', via: [:get, :put, :post]
    match '/products_l' => 'products#index', as: 'l_products', via: [:get]
    match '/products_c' => 'products#index', as: 'c_products', via: [:get]
    match '/products/:id/exists_in_search' => 'products#exists_in_search', as: 'product_exists_in_search', via: [:get, :put, :post]
    match '/products/:id/related' => 'products#related_products', as: 'related_products', via: [:get, :put, :post]
    match '/related_option_types/:record_type/:record_id' => 'api/option_types#related', as: :related_option_types, via: [:get, :put, :post]
    match '/variants/:id/data' => 'products#variant_data', as: 'product_variant_data', via: [:get, :put, :post]
    match '/option_types/load' => 'api/option_types#load', as: :load_option_types, via: [:get, :put, :post]
    match '/admin/taxons/:id/related_option_types', to: 'admin/taxons#related_option_types', as: :taxon_related_option_types, via: [:get]

    #get '/search', to: 'products#index', as: 'search_by_id'
    #get '/search', to: 'searches#show', as: 'search_by_id'

    ##
    # Buyer
    match '/add_item_to_cart' => 'api/v2/storefront/cart#add_item', via: [:put, :post], as: 'populate_orders'
    match '/select_variant' => 'api/v2/storefront/cart#select_variant', via: [:put, :post], as: 'select_variant'
    match '/orders/:id/help' => 'orders#help', via: [:get], as: 'order_help'
    match '/orders/:id/upload_image' => 'orders#upload_image', via: [:patch, :put, :post], as: 'order_upload_image'
    match '/orders/:id/messages/:message_id' => 'orders#show_message', via: [:get], as: 'order_show_message'
    match '/orders/:id/messages' => 'orders#create_message', via: [:get, :put, :post], as: 'order_create_message'
    match '/orders' => 'orders#index', via: [:get], as: 'orders'
    patch "/orders/:id/update_channel", to: "orders#update_channel", as: :update_order_channel


    # Sellers
    get '/payment_methods_provided' => 'store_payment_methods#payment_methods_provided', as: 'payment_methods_provided'
    get '/payment_method_accounts' => 'store_payment_methods#accounts', as: 'payment_method_accounts'

    ##
    # Orders
    get '/recent_sales(.:format)' => 'orders#recent_sales',  as: 'recent_sales'

    # iOffer Landing
    match '/other' => 'home#other_site_accounts', via: [:get], as:'other'
    match '/contact_info' => 'home#payment_info', via: [:get], as: 'contact_info'
    match '/seller_contact_info' => 'home#payment_info', via: [:get], as: 'seller_contact_info'
    match '/payment_options' => 'home#payment_options', via: [:get], as: 'payment_options'
    match '/seller_obligations' => 'home#seller_obligations', via: [:get], as: 'seller_obligations'

    # iOffer Static Pages
    match '/privacy_policy' => 'base#privacy_policy', via: [:get], as:'privacy'
    match '/terms' => 'base#terms_of_use', via: [:get], as:'terms'

    get '/u/:code', to: 'item_reviews#show', as: :item_review
    get '/u/:code/purchases', to: 'item_reviews#purchases', as: :purchases_item_review


    # Must be here for spree home to access path urls
    namespace :ioffer, path: '/' do

      match '/seller_signup' => '/ioffer/users#new', via: [:get], as:'seller_signup'
      match '/payments' => '/ioffer/payment_methods#index', via: [:get], as: 'payments'
      match '/select_payment_methods' => '/ioffer/payment_methods#select_payment_methods', via: [:post, :put, :patch], as:'select_payment_methods'

      match '/save_contact_info' => '/ioffer/payment_methods#save_payment_info', via:[:put, :post], as: 'save_contact_info'

      match '/categories_brands' => '/ioffer/brands#index', via: [:get], as:'brands'
      match '/what_categories' => '/ioffer/brands#index', via: [:get], as:'what_categories'
      match '/select_brands' => '/ioffer/brands#select_brands', via: [:post, :put, :patch], as:'select_brands'
      match '/select_categories' => '/ioffer/categories#select_categories', via: [:post, :put, :patch], as:'select_categories'

      match '/email_subscriptions' => '/ioffer/email_subscriptions#create', via: [:post], as: 'email_subscriptions'
      match '/other_site_accounts' => '/ioffer/other_site_accounts#create', via: [:post]
    end
  end # add_routes

  ##
  # Messages

  namespace :user, path: '/' do
    match 'messages/list' => 'messages#index', via: [:get], as:'messages_list'
    resources :messages
    match 'messages/:id/image/:filename' => 'messages#image', via: [:get], as:'message_image'
    match 'messages/:id/thumb/:filename' => 'messages#thumb', via: [:get], as:'message_thumb'
  end

  ##
  # Search
  resources :search_keywords, only:[:index]

  # Retail
  namespace :retail, path: 'admin/retail' do
    resources :sites
    resources :site_categories, only: [:update, :show, :index]
  end

  # Scraper
  namespace :scraper, path:'admin/scraper' do
    match 'pages/preview(.:format)' => 'pages#preview', as: 'page_preview', via: [:get, :post, :put]
    match 'pages/:id/fetch(.:format)' => 'pages#fetch', as: 'page_fetch', via: [:get, :post, :put]
    match 'pages/:id/show_product(.:format)' => 'pages#show_product_from_saved_page', as:
    'page_show_product', via: [:get, :post, :put]
    match 'pages/:id/source_file(.:format)' => 'pages#source_file', as: 'page_source_file', via: [:get, :post, :put]

    resources :pages
  end

  # iOffer

  namespace :ioffer, path: '/' do
    get '/ioffer/logout' => 'users#logout', as: 'logout'
    resources :users, except: [:destroy]

    get '/seller_onboarding' => 'users#seller_onboarding', as: 'seller_onboarding'
    get '/getting_started' => 'users#getting_started', as: 'seller_getting_started'
    get '/next_after_save' => 'users#next_after_save', as: 'next_after_save'
  end

app/views/home/_category_menu.html.erb
<% # Replacement of spree_navigation_data
    if Spree::CategoryTaxon.top_level_categories.any? %>
    <ul class="nav pl-3 side-cat-bar">
      <% Spree::CategoryTaxon.top_level_categories.each_with_index do |top_category, index| %>
      <% break if index >= 6 %>
      <li class="">
        <%= link_to top_category.name, seo_url(top_category), class: "p-2 main-nav-bar-item main-nav-bar-category-button" %>
      </li>
    <% end # each top_category %>
    </ul>
<% end %>

app/views/home/_logo_and_timeline.html.haml
- content_for :head do
  :css
    .timeline-item h6, .timeline-item h5 {
      font-weight: 700;
      color: #666666;
    }
    .timeline-item.highlighted h6, .timeline-item.highlighted h5 {
      color: #333333;
    }
    .timeline-number {
      justify-content: center !important;
      position: relative;
      margin-bottom: 0.8em;
    }
    .timeline-number .number-badge {
      text-align: center;
      border: solid 2px #333333;
      border-radius: 50%;
      font-weight: 700;
      background-color: white;
      width: 2.4em;
      height: 2.4em;
      line-height: 2.2em;
      z-index: 10;
    }
    .timeline-item.highlighted .number-badge {
      color: white;
      background-color: maroon;
    }
    .timeline-number .middle-bar-from-start-abs {
      border-top: solid 1px #333333;
      width: 50%;
      height: 2px;
      position: absolute;
      left: 0;
      top: 50%;
      z-index: 0;
    }
    .timeline-number .middle-bar-to-end-abs {
      border-top: solid 1px #333333;
      width: 50%;
      height: 2px;
      position: absolute;
      right: 0;
      top: 50%;
      z-index: 0;
    }

.row(id="ioffer_top_header")
  .col-3
    = image_tag('ioffer_logo_color_plain_w200.png', alt:'iOffer', title: spree_current_user.username_or_email.to_s)
  .col-9.mt-3.timeline
    = yield :timeline

app/views/home/brands.html.haml
:ruby
  brand_names = ['gucci', 'louis vuitton', 'nike', 'the north face', 'coach', 'adidas', 'off white', 'prada', 'yves saint laurent', 'tiffany', 'chanel', 'michael kors', 'burberry', 'jordan', 'cartier', 'hermes', 'bulgari', 'yeezy', 'bape', 'rayban']

- content_for :footer do
  :javascript
    function categoryChecking() {
      var wrapper = $(this).parent();
      if ( !wrapper.hasClass('category-card-wrapper')) { wrapper = wrapper.parent(); }
      if ( this.checked ) {
        wrapper.addClass('category-selected');
        wrapper.find("input[type='checkbox']").prop('checked', true);
      }
      else {
        wrapper.removeClass('category-selected');
        wrapper.find("input[type='checkbox']").prop('checked', false);
      }
    }

    function brandChecking() {
      var wrapper = $(this).parent();
      if ( !wrapper.hasClass('brand-card-wrapper')) { wrapper = wrapper.parent(); }
      if ( this.checked ) {
        wrapper.addClass('brand-selected');
      }
      else {
        wrapper.removeClass('brand-selected');
      }
    }

    $(function() {
      $(".category-card-wrapper input[type=checkbox]").change(categoryChecking);
      $(".brand-card-wrapper input[type=checkbox]").change(brandChecking);
    });

= image_tag('i-offer-logo.png', alt:'iOffer')

= form_tag(ioffer_select_brands_path, method: 'post', remote: true, authenticity_token: true) do
  .container
    .row
      .col-8.my-auto.title-container
        .center-title
          .py-5.py-md-0
            %h1.mb-3= t('store.what_categories_do_you_supply')
            %h5.mb-5= t('store.select_all_that_apply')

  .container
    .row
      = category_taxon_card("Women's Clothing", '/categories/dress.svg')
      = category_taxon_card("Men's Clothing", '/categories/shirt.svg')
      = category_taxon_card("Sneakers", '/categories/sneakers.svg')
      = category_taxon_card("Handbags", '/categories/handbag.svg', '', name: 'Bags & Purses')
      = category_taxon_card("Jewelry", '/categories/necklace.svg', '', name: "Jewelry & Watches")
    .row
      = category_taxon_card("Watches", '/categories/watch.svg', '', name: 'Jewelry & Watches')
      = category_taxon_card("Sunglasses", '/categories/sunglasses-2.svg', '', |
        permalink:['categories/womens-clothing/accessories/eyewear-accessories', |
        'categories/mens-clothing/accessories/sunglasses'])
      = category_taxon_card("Makeup", '/categories/make-up.svg')
      = category_taxon_card("Women's Shoes", '/categories/shoe.svg')
      = category_taxon_card("Accessories", '/categories/hat.svg', '', |
        permalink:['categories/womens-clothing/accessories', |
        'categories/mens-clothing/accessories'])
  %br/
  %br/
  - if spree_current_user&.full_seller?
    .container
      .row
        %div(class="col-8 my-auto title-container")
          .center-title
            %div(class="py-5 py-md-0")
              %h1.mb-3= t('store.what_brands_do_you_have')
              %h5.mb-5= t('store.select_all_that_apply')

    .container
      - make_brand_option_value_cards(:name, brand_names)
      = submit_tag(t('store.submit_brands'), class:'btn btn-primary btn-center')
  - else
    .container
      = submit_tag(t('store.submit_categories'), class:'btn btn-primary btn-center')
%br/
%br/

app/views/home/index.html.haml
.bg-img1.size1.flex-w.flex-c-m.p-t-0.p-b-55.p-l-15.p-r-15
  .logo-c
    = image_tag('i-offer-logo.png', alt:'iOffer')
  .div
    .row.p-t-50
      .col
        .wsize1.bor1.bg1.p-t-25.p-b-25.p-l-15.p-r-15.respon1.respon2
          = image_tag("blocked_homepage/homepage-user-signup.png", :class => "header-icon center-in-div", :alt=>"User")
          %p.txt-center.m-t-10
            I want to be notified of iOffer updates.
          = form_for(@email_subscription || Ioffer::EmailSubscription.new, as:'email_subscription', remote: true, html:{ id:'email_subscription_form', class:'flex-w flex-c-m contact100-form validate-form p-t-10 p-b-40'} ) do|f|
            .wrap-input100.validate-input.where1{"data-validate" => "Email is required: ex@abc.xyz"}
              = f.text_field(:email, placeholder:'Your Email', class:'s1-txt2 placeholder0 input100' )
              %span.focus-input100
            = f.submit('Get Notified', class:'flex-c-m s1-txt3 size3 how-btn trans-04 where1', id:'email_subscription_submit')
            - if need_to_captcha_verify?
              .m-t-10
                = recaptcha_wrapper(f.object)
      .col
        .wsize1.bor1.bg1.p-t-25.p-b-25.p-l-15.p-r-15.respon1.respon2
          = image_tag("blocked_homepage/homepage-store-signup.png", :class => "header-icon center-in-div", :alt=>"Vendor")
          %p.txt-center.m-t-10
            I want to sell my products on iOffer.
          %h6.center
            .button.how-btn.trans-04.size3.s1-txt3.m-t-25.center-in-div
              = link_to "Contact us to apply for a seller account", "mailto:apply@ioffer.com", class: "apply-link" 
            -#= button_to("I want to sell on iOffer", ioffer_seller_signup_path, :id => "seller_signup_path-btn", :class => "button how-btn trans-04 size3 s1-txt3 m-t-25 center-in-div", :method => :get)
      .vl
%h6.language-picker

app/views/home/other.html.haml
:css
= image_tag('i-offer-logo.png', alt: "iOffer")
= form_tag(ioffer_other_site_accounts_path, method:'post') do
  .container
    .row
      .col-10.my-auto.title-container
        .center-title
          .py-5.py-md-0
            %h1.mb-3
              Transfer items and rating from
              %b AliExpress
              and
              %b DHgate
            %h5.mb-5
              Provide us with your seller ID and we will import your rating and items for
              = succeed "." do
                %b free
        .input-group.input-group-newsletter
          .url-display AliExpress.com/store/&nbsp;
          %input.form-control{"name"=>"aliexpress_account_id", value:"#{@aliexpress}", "aria-describedby" => "basic-addon", "aria-label" => "Enter information...", :pattern => "[0-9]+", :maxLength => 7, :onkeypress => "validate(event)", :placeholder => "Aliexpress Store ID", :type => "text"}/
        .input-group.input-group-newsletter.mt-1
          .url-display DHgate.com/store/&nbsp;
          %input.form-control{"name"=>"dhgate_account_id", value:"#{@dhgate}", "aria-describedby" => "basic-addon", "aria-label" => "Enter information...", :pattern => "[0-9]+", :maxLength => 8, :onkeypress => "validate(event)", :placeholder => "DHGate Store ID", :type => "text"}/
  %button.btn.btn-primary.btn-center(type='submit') Submit Seller Information
  %h1.separator Submit your CSV
  .row
    .col-10.my-auto.title-container
      .center-title
        %p.mb-5
          Email us a .CSV file of your products and we will import them into your store automatically for
          = succeed "." do
            %b free
  %a.btn.btn-primary.btn-center.mt-0{:href => "mailto:info@ioffer.com?subject=Reopen%20store%20request.&body=Please%20attach%20your%20item%20CSV%20to%20this%20email%20and%20we%20will%20make%20sure%20to%20import%20your%20items."} Send a .CSV
  %a.btn.btn-center.mt-1{:href => "#{ioffer_brands_path}"} Next
%br/
%br/
%br/

app/views/home/payment_info.html.haml
:ruby
  wechat_account_id = spree_current_user.other_site_accounts.where(site_name: 'wechat').first&.account_id
  first_email_from_china = Filter::Domain.domain_from_china?(spree_current_user&.email)

- content_for :head do
  :css
    .modal-dialog { max-width: 60%; }
    .modal-body h4, .modal-body h5 { line-height: 1.5em; }
  :javascript
    var skipValidate = false;
    function doubleCheckForm(e) {
      var form = $(this);
      var validationInput = $("form#user_form").find("input[name='skip_validation']")[0];
      if (validationInput && validationInput.value != 'true') {
        var foundAccountId;
        var foundSecondaryEmail;
        form.find("input").each(function(index, input)
        {
          if (input.value != undefined && input.value.match(/^(\S+)$/) != null) {

            if (input.name.startsWith("user[other_site_account[") ) {
              foundAccountId = input.value;
            }
            else if (input.name == 'user[secondary_email]') {
              foundSecondaryEmail = input.value;
              #{'if (!checkSecondaryEmail(input)) { e.preventDefault(); };' if first_email_from_china}
            }
          }
        });
        if (foundAccountId || foundSecondaryEmail) {
        } else {
          $('#payment_form_warning').modal('show');
          skipValidate = true;
          if (validationInput) { validationInput.value = 'true'; }
          e.preventDefault();
        }
      }
      else {
        // skip validation
      }
    }

    function checkSecondaryEmail(input) {
      var validDomain = /#{Filter::Domain::DOMAINS_OF_CHINA_REGEXP.source}/i;
      if (input.value && input.value.match(validDomain) ) {
        $(input).addClass('is-invalid');
        $(input).select();
        $(input).siblings('h5').hide();
        $(input).siblings('h5.text-danger').show();
        return false;
      } else {
        return true;
      }
    }

- content_for :footer do
  :javascript
    $(function(){
      $("#user_form").submit(doubleCheckForm);
    });

- content_for :timeline do
  = timeline_table do|timeline|
    - timeline.step 1, t('user.registration'), true
    - timeline.step 2, t('user.contact_info'), true
    - timeline.step 3, t('user.payment_methods.payment_options'), false
    - timeline.step 4, t('store.list_items'), false
.container
  = render partial:'home/logo_and_timeline'
  .mt-3 &nbsp;
  = form_tag(admin_payment_methods_and_retail_stores_path, method:'post', id:'user_form') do
    = hidden_field_tag('skip_validation', false)
    = hidden_field_tag('next_path', payment_options_path)
    %div(class="row")
      .col-3.col-xs-1
      .col-6.col-xs-10
        .text-center.mb-3
          %h5= t('user.payment_methods.for_quicker_support')
        .mb-5
          = text_field_tag("other_site_accounts[wechat]", wechat_account_id, class:'form-control form-control-lg form-payment highlighted-form', 'aria-describedby'=>'basic-addon', 'aria-label'=>'Enter account', placeholder: I18n.t('user.payment_methods.your_service_id', service: 'WeChat') )
        .text-center.mb-5
          %h5.font-weight-500
            = t('user.payment_methods.please_add')
            %strong iOfferHelp
            = t('user.payment_methods.to_your_service_id', service: 'WeChat')
          %br/
          = image_tag( asset_path('payment_methods/add_iofferhelp_in_wechat.png'), alt:'Add iOfferHelp to WeChat')
        .text-center.mb-5
          = text_field_tag('user[secondary_email]', spree_current_user&.secondary_email, class:'form-control form-control-lg mb-3 highlighted-form', placeholder: first_email_from_china ? t('user.non_mainland_email_address') : t('user.secondary_email') )
          - if first_email_from_china
            %h5= t('user.example_non_mainland_emails')
          %h5.text-danger(style="display: none;")= t('user.contact_you_by_secondary_email')
        %div
          = submit_tag(t('form.submit'), class:'btn btn-primary btn-lg form-control center-in-div', data:{ disable_with: t('form.submitting') } )

  .row.mb-5
    %br/

= render partial:'spree/admin/shared/modal.html.haml', locals:{ target:'payment_form_warning', content: "<div class='mt-3 mb-3 p-3'><h4>#{t('user.payment_methods.sales_notifications_quicker', service: 'WeChat') }</h4></div>" }

app/views/home/payment_options.html.haml
:ruby
  payment_method = Spree::PaymentMethod.paypal
  @store_payment_method ||= @store_payment_methods.find{|spm| spm.payment_method_id == payment_method.id }
  requires_this_pm = spree_current_user&.full_seller?

- content_for :head do
  :css
    .modal-dialog { max-width: 60%; }
    .modal-body h4, .modal-body h5 { line-height: 1.5em; }
  :javascript
    var skipValidate = false;
    function doubleCheckForm(e) {
      var form = $(this);
      var validationInput = $("form#store_payment_methods_form").find("input[name='skip_validation']")[0];
      var accountIdInput;
      if (validationInput && validationInput.value != 'true') {
        var foundAccountId;
        var foundInstruction;
        form.find("input,textarea").each(function(index, input)
        {
          if (input.value != undefined && input.value.match(/^(\S+)$/) != null) {

            if (input.name.startsWith("payment_method_account_ids") ) {
              foundAccountId = input.value;
              accountIdInput = input;
            }
            else if (input.name.startsWith("store_payment_method_instruction") ) {
              foundInstruction = input.value;
            }
          }
        });
        if (foundAccountId || foundInstruction) {

        } else {
          $('#payment_form_warning').modal('show');
          skipValidate = true;
          if (validationInput) { validationInput.value = 'true'; }
          if (accountIdInput) { accountIdInput.attr('required', false); }
          e.preventDefault();
        }
      }
    }

- content_for :footer do
  :javascript
    $(function(){
      $("#store_payment_methods_form").submit(doubleCheckForm);
    });

- content_for :timeline do
  = timeline_table do|timeline|
    - timeline.step 1, t('user.registration'), true
    - timeline.step 2, t('user.contact_info'), true
    - timeline.step 3, t('user.payment_methods.payment_options'), true
    - timeline.step 4, t('store.list_items'), false

.container
  = render partial:'home/logo_and_timeline'
  .mt-3 &nbsp;
  = form_tag(admin_payment_methods_and_retail_stores_path, method:'post', id:'store_payment_methods_form') do
    = hidden_field_tag('skip_validation', false)
    = hidden_field_tag('current_path', 'home/payment_options')
    = hidden_field_tag('next_path', payment_methods_provided_path)
    %div(class="row")
      .col-3.col-xs-1
      %div(id="payment_input_#{payment_method.id}" class="col-6 col-xs-10 payment-input")
        %h2.mb-5= t('user.payment_methods.buyers_want_to_pay_with', service: payment_method.description)
        .mb-5.text-center
          %h5.mb-1= t('user.payment_methods.please_enter_your_email', service: payment_method.description)
          = email_field_tag("payment_method_account_ids[#{payment_method.id}]", @store_payment_method&.account_id_in_parameters, class:"form-control form-control-lg form-payment highlighted-form#{' is-invalid' if @store_payment_method && @store_payment_method.errors[:account_parameters]&.first }", 'aria-describedby'=>'basic-addon', placeholder: t('user.payment_methods.your_service_email', service: payment_method.description), required: true )
          - if @store_payment_method && ( warning = @store_payment_method.errors[:account_parameters]&.first ).present?
            %h6.text-danger.text-dark-warning.mt-2.mb-3= warning
        .mb-3.text-center
          %h5.mb-1= t('user.payment_methods.payment_instruction_note')
          = text_area_tag("store_payment_method_instruction_#{payment_method.id}", @store_payment_method&.instruction, class:'form-control form-control-lg form-payment highlighted-form', 'aria-describedby'=>'basic-addon' )

        %div(style="height: 10%;") &nbsp;
        .mb-3
          %h5.font-weight-default= t('user.payment_methods.recommend_setting_up_service', service: payment_method.description)
        = submit_tag(t('form.submit'), class:'btn btn-primary btn-lg form-control center-in-div', data:{ disable_with: t('form.submitting') } )
        .mt-5.text-right
          = link_to(t('payment.other_payment_methods') + ' >>', payment_methods_provided_path)
      .col-3.col-xs-1
  .mb-5 &nbsp;

= render partial:'spree/admin/shared/modal.html.haml', locals:{ target:'payment_form_warning', content: "<div class='mt-3 mb-3 p-3'><h4>#{t('user.payment_methods.customers_prefer_payment', service: payment_method.description) }</h4></div>" }