config/routes.rb
      match 'critical_response', to: 'stores#critical_response', as: :critical_response, via: [:get, :put, :post]
      match 'update_options', to: 'stores#update_options', as: :update_options, via: [:put, :post]
      match 'soft_delete_user/:id', to: 'users#soft_delete', as: :soft_delete_user, via: [:put, :post]
      match 'restore/:id', to: 'users#restore', as: :restore_user, via: [:put, :post]
      match 'limit_user/:id', to: 'users#limit_user', as: :limit_user, via: [:put, :post]
      match 'remove_limit/:id', to: 'users#remove_limit', as: :remove_limit, via: [:put, :post]
      match 'niir/:version', to: 'record_reviews#products', as: :niir_version, via: [:get]
      match 'niir', to: 'record_reviews#products', as: :niir, via: [:get]
      match 'record_reviews/mark_reviewed', to: 'record_reviews#mark_reviewed', as: 'mark_record_reviewed', via: [:get, :put]

      match 'remove_user_list_user/:id', to: 'user_lists#remove_user', as: 'remove_user_list_user', via: [:put, :post, :delete]
      match 'remove_product_list_product/:id', to: 'product_lists#remove_product', as: 'remove_product_list_product', via: [:put, :post, :delete]
      resources :user_lists
      resources :record_reviews
      resources :product_lists

      # Product manager
      match '/product_manager/preview_takedown' => 'product_manager#preview_takedown', as: 'preview_takedown', via: [:put, :post, :delete]
      match '/product_manager/takedown' => 'product_manager#takedown', as: 'takedown', via: [:put, :post, :delete]
      get '/product_manager' => 'product_manager#index', as: 'product_manager'

      # Products
      match '/wanted_products', to: 'stores#find_and_list_items', as: 'wanted_products', via: [:get]
      match '/listing_policy', to: 'stores#update_listing_policy', as: 'update_item_listing_policy', via: [:put, :post]
      match '/listing_policy', to: 'stores#listing_policy', as: 'item_listing_policy', via: [:get]
      match '/find_and_list_items', to: 'stores#find_and_list_items', as: 'find_and_list_items', via: [:get]
      match '/products/:id/list_same_item' => 'products#list_same_item', as: 'list_same_item', via: [:get]
      match '/products/:id/list_variants' => 'products#list_variants', as: 'list_variants', via: [:put, :post]

      match 'other_listings', to: 'products#adopted', as: 'other_listings', via: [:get]
      match 'products_adopted', to: 'products#adopted', as: 'products_adopted', via: [:get]
      match '/products/top_selling', to: 'products#top_selling', as: 'products_top_selling', via: [:get]
      match 'products/toggle_selling_taxon', to: 'products#toggle_selling_taxon', as: 'toggle_selling_taxon', via: [:get, :put, :post]
      match 'products/:id/erase', to: 'products#erase', as: 'erase_product', via: [:delete]
      match '/products/:id/debug' => 'products#show_debug', as: 'product_debug', via: [:get, :put, :post]

      match 'products/:product_id/images/:id/mark_as_main', to: 'images#mark_as_main', as: 'mark_image_as_main', via: [:get, :put, :post]
      match 'products/:product_id/upload_images/:id', to: 'images#delete_image', as: 'product_delete_image', via: [:delete]
      match 'products/:product_id/upload_images', to: 'images#upload_images', as: 'product_upload_images', via: [:put, :post]
      match 'products_batch_update' => 'products#batch_update', as: 'batch_update_products', via: [:put, :post]


      ##
      # Seller
      match '/orders/:id/preview_invoice_email' => 'orders#preview_invoice_email', as:'order_preview_invoice_email', via: [:get]

      # Orders
      match '/orders/:id/update_messages' => 'orders#update_messages', via: [:put, :post], as: 'order_update_messages'
      match '/orders/:id' => 'orders#show', as:'order', via:[:get]
      match '/sales/:state' => 'orders#sales', as:'sales_in_state', via: [:get]
      match '/sales' => 'orders#sales', as:'sales', via: [:get]
      match '/msales' => 'orders#mobile_sales', as:'mobile_sales', via: [:get]

      # Store
      match '/payment_methods_and_retail_stores' => 'store_payment_methods#save_payment_methods_and_retail_stores', as:'payment_methods_and_retail_stores', via: [:get, :put, :post]
      match '/store_payment_methods/toggle' => 'store_payment_methods#toggle', as: 'toggle_store_payment_method', via: [:get, :put, :post]
      resources :store_payment_methods, only:[:index, :show, :update]
      get '/fill_your_shop' => 'stores#fill_your_shop', as: 'fill_your_shop'

      # Imports
      match '/scraper_page_imports/select(.:format)' => 'scraper_page_imports#select', as: 'select_scraper_page_imports', via: [:post, :put]
      match '/products/imported' => 'scraper_page_imports#products', as: 'imported_products', via: [:get]
      match 'scraper_page_imports' => 'scraper_page_imports#products', as: 'page_product_imports', via: [:get]

    end


    # Users
    get Spree.admin_path => 'admin/base#home', as: :admin_default

    get '/account' => 'users#account', as: 'account'
    match '/onboarding/:passcode/password' => 'users#onboarding_change_password', as: 'onboarding_change_password', via: [:get, :put, :post, :patch]
    get '/onboarding/:passcode' => 'users#onboarding', as: 'user_onboarding'

    get '/users/info' => 'admin/users#show', as: 'users_info'
    get '/users/:username' => 'home#not_found', as: 'users_detail'

    devise_scope :spree_user do
      match '/admin/sign_in_as/:id' => 'user_sessions#sign_in_as', as:'admin_sign_in_as', via: [:get, :put, :post]
    end

    ##
    # Products
    match '/products_s' => 'products#index', as: 's_products', via: [:get, :put, :post]
    match '/products_m' => 'products#index', as: 'm_products', via: [:get, :put, :post]
    match '/products_sd' => 'products#index', as: 'sd_products', via: [:get, :put, :post]
    match '/products_md' => 'products#index', as: 'md_products', via: [:get, :put, :post]
    match '/products_l' => 'products#index', as: 'l_products', via: [:get]
    match '/products_c' => 'products#index', as: 'c_products', via: [:get]
    match '/products/:id/exists_in_search' => 'products#exists_in_search', as: 'product_exists_in_search', via: [:get, :put, :post]
    match '/products/:id/related' => 'products#related_products', as: 'related_products', via: [:get, :put, :post]
    match '/related_option_types/:record_type/:record_id' => 'api/option_types#related', as: :related_option_types, via: [:get, :put, :post]
    match '/variants/:id/data' => 'products#variant_data', as: 'product_variant_data', via: [:get, :put, :post]
    match '/option_types/load' => 'api/option_types#load', as: :load_option_types, via: [:get, :put, :post]
    match '/admin/taxons/:id/related_option_types', to: 'admin/taxons#related_option_types', as: :taxon_related_option_types, via: [:get]

    #get '/search', to: 'products#index', as: 'search_by_id'
    #get '/search', to: 'searches#show', as: 'search_by_id'

    ##
    # Buyer
    match '/add_item_to_cart' => 'api/v2/storefront/cart#add_item', via: [:put, :post], as: 'populate_orders'
    match '/select_variant' => 'api/v2/storefront/cart#select_variant', via: [:put, :post], as: 'select_variant'
    match '/orders/:id/help' => 'orders#help', via: [:get], as: 'order_help'
    match '/orders/:id/upload_image' => 'orders#upload_image', via: [:patch, :put, :post], as: 'order_upload_image'
    match '/orders/:id/messages/:message_id' => 'orders#show_message', via: [:get], as: 'order_show_message'
    match '/orders/:id/messages' => 'orders#create_message', via: [:get, :put, :post], as: 'order_create_message'
    match '/orders' => 'orders#index', via: [:get], as: 'orders'
    patch "/orders/:id/update_channel", to: "orders#update_channel", as: :update_order_channel


    # Sellers
    get '/payment_methods_provided' => 'store_payment_methods#payment_methods_provided', as: 'payment_methods_provided'
    get '/payment_method_accounts' => 'store_payment_methods#accounts', as: 'payment_method_accounts'

    ##
    # Orders
    get '/recent_sales(.:format)' => 'orders#recent_sales',  as: 'recent_sales'

    # iOffer Landing
    match '/other' => 'home#other_site_accounts', via: [:get], as:'other'
    match '/contact_info' => 'home#payment_info', via: [:get], as: 'contact_info'
    match '/seller_contact_info' => 'home#payment_info', via: [:get], as: 'seller_contact_info'
    match '/payment_options' => 'home#payment_options', via: [:get], as: 'payment_options'
    match '/seller_obligations' => 'home#seller_obligations', via: [:get], as: 'seller_obligations'

    # iOffer Static Pages
    match '/privacy_policy' => 'base#privacy_policy', via: [:get], as:'privacy'
    match '/terms' => 'base#terms_of_use', via: [:get], as:'terms'

    get '/u/:code', to: 'item_reviews#show', as: :item_review
    get '/u/:code/purchases', to: 'item_reviews#purchases', as: :purchases_item_review


    # Must be here for spree home to access path urls
    namespace :ioffer, path: '/' do

      match '/seller_signup' => '/ioffer/users#new', via: [:get], as:'seller_signup'
      match '/payments' => '/ioffer/payment_methods#index', via: [:get], as: 'payments'
      match '/select_payment_methods' => '/ioffer/payment_methods#select_payment_methods', via: [:post, :put, :patch], as:'select_payment_methods'

      match '/save_contact_info' => '/ioffer/payment_methods#save_payment_info', via:[:put, :post], as: 'save_contact_info'

      match '/categories_brands' => '/ioffer/brands#index', via: [:get], as:'brands'
      match '/what_categories' => '/ioffer/brands#index', via: [:get], as:'what_categories'
      match '/select_brands' => '/ioffer/brands#select_brands', via: [:post, :put, :patch], as:'select_brands'
      match '/select_categories' => '/ioffer/categories#select_categories', via: [:post, :put, :patch], as:'select_categories'

      match '/email_subscriptions' => '/ioffer/email_subscriptions#create', via: [:post], as: 'email_subscriptions'
      match '/other_site_accounts' => '/ioffer/other_site_accounts#create', via: [:post]
    end

app/models/spree/order/actions.rb
module Spree::Order::Actions
  extend ActiveSupport::Concern

  #########################
  # Actions

  # @create_anyway for case that would need manual call instead of auto after callbacks.
  def create_initial_message!(create_anyway = false)
    msg = User::NewOrder.find_or_initialize_by( User::Message.conditions_for_record(self) )
    msg.sender_user_id ||= user_id
    msg.recipient_user_id ||= seller_user_id
    msg.save
    msg
  end

  def update_highest_message_level!
    self.update_columns(highest_message_level: self.messages.order('level desc').first&.level )
  end

  ##
  # Available public for making up existing orders.
  # @create_anyway for case that would need manual call instead of auto after callbacks.
  def create_message!(create_anyway = false)
    msg = nil
    if state_changed? && complete?
      create_initial_message!
    end
    if payment_state_changed?
      if Spree::Order::PAID_PAYMENT_STATES.include?(payment_state)
        msg = User::OrderPaymentPaid.new( User::OrderMessage.conditions_from_buyer(self) )
      elsif %w(failed).include?(payment_state)
        msg = User::OrderPaymentFailed.new( User::OrderMessage.conditions_from_buyer(self) )
      end
    end
    if approved_at_changed? && approved_at
      msg = User::OrderPaymentConfirmed.new( User::OrderMessage.conditions_from_seller(self) )
    end
    if shipment_state_changed?
      # Possible ready msg
      if shipment_state == 'shipped'
        msg = User::OrderShipped.new( User::OrderMessage.conditions_from_seller(self) )
      end
    end
    if msg
      msg.sender_user_id ||= user_id
      msg.recipient_user_id ||= seller_user_id
      msg.save
    end
    # undefined seller would stay nil
    msg
  end

  # handle_asynchronously :create_message! if Rails.env.production?

  ##
  # Could be state_machine callback, but cannot figure out how to add to existing state_machines definition.
  def check_to_auto_jump
    if state == 'payment'
      if payments.valid.count > 0 # auto jump payment set
        payments.update_all(amount: self.total)
        self.next
      end
    end
  end

  def notify_users
    if state == 'complete'
      send_invoice_to_buyer unless confirmation_delivered
      if seller
        send_order_to_seller
        if Rails.env.production?
          seller.delay(
            queue: Spree::User::NOTIFY_EMAIL_DJ_QUEUE, run_at: Spree::User::NOTIFY_EMAIL_DELAY_LENGTH.after ).notify_about_pending_orders
        else
          seller.notify_about_pending_orders
        end
      end
    end
  end

  def send_order_to_seller
    return if seller.nil? || seller.phantom_seller? || (Rails.env.production? && !seller.hp_seller? && !seller.approved_seller?)

    Spree::OrderMailer.with(order: self).new_order_to_seller.deliver

  rescue Exception => e
    UserReport::EmailDelivery.report_delivery_error(self, e, seller_user_id)
  end
  handle_asynchronously :send_order_to_seller, queue: Spree::User::NOTIFY_EMAIL_DJ_QUEUE if Rails.env.production?


  def send_invoice_to_buyer(resend = false)
    return true if self.user.nil? || self.user.fake_user? || self.seller.nil? || self.seller.phantom_seller?

    subject_prefix = (resend ? "[#{Spree.t(:resend).upcase}] " : '')
    Spree::OrderMailer.with(order: self, subject_prefix: subject_prefix).invoice_to_buyer.deliver
    self.update_attributes(invoice_last_sent_at: Time.now, confirmation_delivered: true)
  rescue Exception => e
    UserReport::EmailDelivery.report_delivery_error(self, e, user_id)
    raise e
  end
  handle_asynchronously :send_invoice_to_buyer, queue: Spree::User::NOTIFY_EMAIL_DJ_QUEUE if Rails.env.production?


  ##
  # For each line item's product, call to update best variant
  def update_products!
    line_items.includes(:product).each do|line_item|
      next if line_item.product.nil?
      should_recal = (line_item.product.transaction_count.to_i % 10 == 9) # every 10 recal
      line_item.product&.update_columns(transaction_count: (should_recal ? line_item.product.calculate_transaction_count : line_item.product.transaction_count.to_i + 1 ) )
    end
  end

  handle_asynchronously :update_products!, queue:'AFTER_ORDER_ITEM_STATS' if Rails.env.production?

end

app/controllers/spree/admin/orders/customer_details_controller_decorator.rb
module Spree::Admin::Orders::CustomerDetailsControllerDecorator
  def self.prepended(base)
    base.include ControllerHelpers::SellerManager
  end
end

Spree::Admin::Orders::CustomerDetailsController.prepend(Spree::Admin::Orders::CustomerDetailsControllerDecorator) if Spree::Admin::Orders::CustomerDetailsController.included_modules.exclude?(Spree::Admin::Orders::CustomerDetailsControllerDecorator)

app/views/spree/admin/orders/_add_tracking_number.html.haml
:ruby
  # Required locals
  #   order [Spree::Order]
  # Optional locals:
  #   add_or_correct: [String] default: 'add'
  add_or_correct = 'add' unless defined?(add_or_correct) && add_or_correct == 'correct'
  critical_response = @critical_response || request.path.starts_with?('/admin/critical_response')
- order.line_items.includes(:product, variant:[:option_values =>[:option_type] ]).sort{|x,y| y.price <=> x.price }.each_with_index do|line_item, index|
  - product = line_item.product
  %div(class="container order-info-table" id="#{index > 0 ? "row_of_#{order.id}_#{line_item.product_id}" : "first_row_of_#{order.id}"}")
    .row
      .col-1
      .col-2
        - if product
          - image = default_image_for_product_or_variant(product)
          = image_tag cdn_image_url(image, :small), style:'max-width: 100%;'
      .col-8.text-left
        - if product
          - size_option_types = line_item.variant.option_values.collect(&:option_type).find_all(&:size?)
          - uniq_cont_of_option_types = line_item.variant.option_values.collect(&:option_type_id).uniq.size
          %strong= link_to product.name, product_path(product), target:'_blank'
          %br/
          = line_item.variant.option_values.collect(&:presentation).join(' - ')
          %br/
        %span.text-secondary= distance_of_time_in_shorts(order.completed_at) + ' ago'
    .row
      .col-1
      .col-2
        - if order.user&.country_code.present?
          %span.country-icon(title="#{order.user.country}")
            = inline_svg_tag "flags/4x3/#{order.user.country_code.downcase}.svg", size: '2.6em*1.3em'
        - else
          %span.country-name= order.user&.country
      .col-8.text-left
        %strong= link_to(order.user.email)
        %br/
        - if (address = order.ship_address)
          %span #{address.full_name} #{address.last_name}
          %br/
          = address.full_address(',<br/>').html_safe
    = form_tag(order_create_message_path(id: order.number), method: :post, multipart: true) do
      = hidden_field_tag(:type, "order_#{add_or_correct == 'correct' ? 'corrected' : 'provided'}_tracking_number")
      - if critical_response
        = hidden_field_tag(:critical_response, true)
        = hidden_field_tag(:return_url, "/admin/critical_response?t=#{Time.now.to_i}")
      .row
        .col-12
          = text_field_tag :comment, '', class:'w-100 form-control', style:"margin: 1.0em 0; padding: 1.4em; line-height: 1.2em; border-radius: 0.8em; border-width: 0.2em;", placeholder: t('order.tracking_number'), required: true
      .row
        .col-2
        .col-8
          = submit_tag('Submit', class:'w-100 btn btn-primary text-uppercase', data: { disable_with:'Sending'})

app/views/spree/admin/orders/_address_row.html.haml
:ruby
  # Required locals
  #   address [Spree::Address]
  # Optional locals
  #   row_attributes [Hash] the HTML attributes in the TR tag; keys as Symbol
  row_attributes ||= {} unless defined?(row_attributes)
-# %tr(id="#{full_info_id}" class="collapse #{order_row_class}")
= tag.tr row_attributes do
  %td(colspan="3")
    %table.address-table
      %tbody
        %tr
          %td= t('user.name')
          %td
            %strong= address.full_name  
        %tr
          %td
            #{ t('user.address.street') } 
            #{ t('user.address.apartment') } 
          %td
            %strong= [address.address1, address.address2].compact.join(' ')
        %tr
          %td= Spree.t('activerecord.attributes.spree/address.city')
          %td
            %strong= address.city
        %tr
          %td= t('user.address.state_or_providence')
          %td
            %strong= address.state&.abbr
            %strong= address.zipcode
        %tr
          %td= Spree.t('activerecord.attributes.spree/address.country')
          %td
            %strong= address.country

app/views/spree/admin/orders/_order_in_list.html.haml
:ruby
  # Builds a row of columns containing list of line items, w/ 1st having buyer info, payment.
  # Required locals
  #   order [Spree::Order]
  # Optional locals
  #   show_full_info [Boolean] whether to show other products in order.line_items
  #   show_actions_in_order_info [Boolean] default true; the links and tracking buttons in order-info-table
  #   image_link_content [Symbol] to be passed _messages_list
  #   specific_user_id [Integer] this helps skip need of seller info for each order
  #   specific_product_id [Integer] this would only show certain product
  full_info_id = "full_user_info_#{order.id}" unless defined?(full_info_id) && full_info_id
  show_full_info = false unless defined?(show_full_info)
  show_actions_in_order_info = true unless defined?(show_actions_in_order_info) && show_actions_in_order_info == false
  image_link_content = :icon unless defined?(image_link_content)
  has_warning = nil unless defined?(has_warning)

  is_viewer_admin = is_admin?
  is_viewer_seller = (spree_current_user&.id == order.seller_user_id)
  can_view_seller_info = (is_viewer_admin || is_viewer_seller)
  specific_user_id = nil unless defined?(specific_user_id)
  specific_product_id = nil unless defined?(specific_product_id)
  right_side_cols = is_viewer_seller && show_actions_in_order_info ? ['col-6 col-md-3', 'col-6 col-md-3'] :
    ['col-10 col-md-3', 'col-2 col-md-3']

  paypal_store_pm = order.seller&.store&.paypal_store_payment_method
  @cached_counts_of_paid_need_tracking ||= {}
  count_of_paid_need_tracking ||= @cached_counts_of_paid_need_tracking[order.seller&.id]
  if count_of_paid_need_tracking.nil?
    count_of_paid_need_tracking = paypal_store_pm&.orders_with_paid_need_tracking_of_same_payment_method_account&.count.to_i
    @cached_counts_of_paid_need_tracking[order.seller&.id] = count_of_paid_need_tracking
  end

- order.line_items.includes(:product, variant:[:option_values =>[:option_type] ]).sort{|x,y| y.price <=> x.price }.each_with_index do|line_item, index|
  - next if specific_product_id && line_item.product_id != specific_product_id
  - product = line_item.product
  %div(class="container order-info-table" id="#{index > 0 ? full_info_id : "first_row_of_#{order.id}"}")
    .row
      .col-2.col-md-1
        - if index == 0
          %strong= '$%.2f' % [order.total]
          %br/
          .text-secondary
            - payment_payment_method = order.payments.first&.payment_method
            - if is_viewer_admin && (store_pm = order.seller&.store&.store_payment_methods.to_a.find{|spm| spm.payment_method_id == payment_payment_method&.id })
              = link_to payment_payment_method&.description, admin_all_sellers_path(q:{ payment_method_id_eq: store_pm.payment_method_id, store_store_payment_methods_account_parameters_cont: store_pm.account_id_in_parameters })
            - else
              = payment_payment_method&.description
        - if is_viewer_admin
          %small(title='Current view count when added to cart') #{line_item.current_view_count || '--'} Views
      .col-9.col-md-5
        .row
          .col-3
            - if product && (default_image = default_image_for_product_or_variant(product) )
              = link_to product_path(product), target:'_blank' do
                = image_tag cdn_image_url(default_image, :pdp_thumbnail), style:'max-width: 100%;'
          .col-9.p-0
            - if index == 0
              %strong
                - if show_actions_in_order_info
                  = link_to order.number, admin_order_path(order), title:"Order ID #{order.id} at #{order.completed_at&.to_mid_s}"
                - else
                  = order.number
              %br/
            - if product
              - size_option_types = line_item.variant.option_values.collect(&:option_type).find_all(&:size?)
              - uniq_cont_of_option_types = line_item.variant.option_values.collect(&:option_type_id).uniq.size
              %strong
                - if show_actions_in_order_info
                  = link_to product.name, product_path(product), target:'_blank'
                - else
                  = product.name
              %br/
              - if is_viewer_admin && product.retail_site
                #{product.retail_site&.name}
                %br/
              - if line_item.variant.present? && variant_options_text(line_item.variant, present_with_option_type: false, exclude_option_types_anyway: true).present?
                %span.variant-size-pill
                  = variant_options_text(line_item.variant, present_with_option_type: false, exclude_option_types_anyway: true)
              %br/
            %span.text-secondary(title="At #{order.completed_at&.to_mid_s}")= distance_of_time_in_abbr(order.completed_at) + ' ago'
      - if index == 0
        %div(class="#{right_side_cols[0] }")
          - if order.user&.country_code.present?
            %span.country-icon(title="#{order.user.country}")
              = inline_svg_tag "flags/4x3/#{order.user.country_code.downcase}.svg", size: '2.6em*1.3em'
          - else
            %span.country-name= order.user&.country
          %span
            %strong
              - if is_viewer_admin && show_actions_in_order_info
                = link_to order.user.email, spree.items_admin_user_path(order.user)
              - else
                = order.user.email
            %br/
            - if (address = order.ship_address)
              %span #{address.full_name}
              - if is_viewer_admin && order.channel == "whatsapp"
                = image_tag "icon/whatsapp/Digital_Glyph_Green.svg", alt: "WhatsApp", class: "whatsapp-icon ml-1", style: "width: 24px; height: 24px;"
              - elsif is_viewer_admin && order.channel == "email"
                = image_tag "icon/backend-envelope.svg", alt: "Emailed", class: "ml-1", style: "width: 24px; height: 20px;"
              %br/
              = is_viewer_admin ? '' : address.full_address(',<br/>').html_safe
            - if is_viewer_admin
              - if line_item.referer_url.present?
                = link_to parse_referer_url(line_item.referer_url), line_item.referer_url, title: line_item.referer_url, target:'_blank'
              %br/
              %span{ id: "copy-ip", style: "cursor: pointer; position: relative;", onclick: "copyToClipboard(this)" }
                = line_item.request_ip.presence || order.user.current_sign_in_ip
                %span{ class: "copy-tooltip", style: "visibility: hidden; background-color: black; color: white; text-align: center; border-radius: 5px; padding: 5px; position: absolute; bottom: 25px; left: 50%; transform: translateX(-50%); font-size: 12px; white-space: nowrap;" }
                  Copied!

        %div(class="#{right_side_cols[1] } text-right")
          - if is_viewer_seller
            - if !show_actions_in_order_info
            - elsif order.claimed_broken_tracking?
              %strong(class="text-dark-warning")
                #{ t('order.tracking_broken') }:
                %a(href="http://www.google.com/search?q=#{order.latest_tracking_number}" target='_blank' rel="noreferrer")= order.latest_tracking_number
              = render partial:'spree/admin/shared/modal', locals:{ target:"order_message_thread_add_tracking_#{order.id}", show_footer: false, partial:'spree/admin/orders/add_tracking_number', partial_locals:{ order: order, add_or_correct:'correct' } }
            - elsif order.requested_tracking?
              %button(class='btn bg-dark-warning' data-toggle='modal' data-target="#order_message_thread_add_tracking_#{order.id}")= t('order.add_tracking_number')
              = render partial:'spree/admin/shared/modal', locals:{ target:"order_message_thread_add_tracking_#{order.id}", show_footer: false, partial:'spree/admin/orders/add_tracking_number', partial_locals:{ order: order, add_or_correct:'add' } }
          - elsif is_viewer_admin
            - if specific_user_id == order.seller_user_id # Tracking info
              - if order.latest_tracking_number.present?
                .text-small
                  Tracking:
                %strong= link_to order.latest_tracking_number, "https://www.google.com/search?q=#{order.latest_tracking_number}", target:'_blank', rel:'noreferrer'
                %br/
                - if order.claimed_broken_tracking?
                  %strong.text-small.text-dark-warning Broken Tracking Number
              - elsif order.requested_tracking?
                %strong.text-small.text-dark-warning Tracking Needed
            - elsif order.seller
              .text-small
                = render partial:'spree/admin/users/payment_service_complaint_info', locals:{ user: order.seller, show_paypal_info: false, show_complaint_ratio: false }
                %br/
                = user_id_link_with_roles_stylized(order.seller).html_safe
                = country_icon_or_name(order.seller)
              %div(style="font-size: 2.0em; margin-right: 0.5em;")
                - if count_of_paid_need_tracking == 0
                  %span(class='text-secondary' title='Paid Neeed Tracking of Same Paypal Account')= count_of_paid_need_tracking
                - else
                  = link_to(count_of_paid_need_tracking, paypal_store_pm ? admin_sales_in_state_path(state: 'paid_need_tracking', store_payment_method_id: paypal_store_pm.id) : '#', title:'Paid Neeed Tracking of Same Paypal Account', style:"color: #{count_of_paid_need_tracking > 5 ? 'red' : '#666666'};")

%div(id="order_messages_#{order.id}" class="container order-messages-table")
  = render partial:'spree/orders/messages_list', locals:{ order: order, show_user_and_timestamp: true, image_link_content: image_link_content, has_warning: has_warning }

:javascript
  function copyToClipboard(element) {
    var text = element.innerText;
    navigator.clipboard.writeText(text).then(() => {
      let tooltip = element.querySelector(".copy-tooltip");
      tooltip.style.visibility = "visible";
      setTimeout(() => {
        tooltip.style.visibility = "hidden";
      }, 1000); // Hide after 1 second
    }).catch(err => {
      console.error('Error copying text: ', err);
    });
  }