config/routes.rb
      match 'remove_product_list_product/:id', to: 'product_lists#remove_product', as: 'remove_product_list_product', via: [:put, :post, :delete]
      resources :user_lists
      resources :record_reviews
      resources :product_lists

      # Product manager
      match '/product_manager/preview_takedown' => 'product_manager#preview_takedown', as: 'preview_takedown', via: [:put, :post, :delete]
      match '/product_manager/takedown' => 'product_manager#takedown', as: 'takedown', via: [:put, :post, :delete]
      get '/product_manager' => 'product_manager#index', as: 'product_manager'

      # Products
      match '/wanted_products', to: 'stores#find_and_list_items', as: 'wanted_products', via: [:get]
      match '/listing_policy', to: 'stores#update_listing_policy', as: 'update_item_listing_policy', via: [:put, :post]
      match '/listing_policy', to: 'stores#listing_policy', as: 'item_listing_policy', via: [:get]
      match '/find_and_list_items', to: 'stores#find_and_list_items', as: 'find_and_list_items', via: [:get]
      match '/products/:id/list_same_item' => 'products#list_same_item', as: 'list_same_item', via: [:get]
      match '/products/:id/list_variants' => 'products#list_variants', as: 'list_variants', via: [:put, :post]

      match 'other_listings', to: 'products#adopted', as: 'other_listings', via: [:get]
      match 'products_adopted', to: 'products#adopted', as: 'products_adopted', via: [:get]
      match '/products/top_selling', to: 'products#top_selling', as: 'products_top_selling', via: [:get]
      match 'products/toggle_selling_taxon', to: 'products#toggle_selling_taxon', as: 'toggle_selling_taxon', via: [:get, :put, :post]
      match 'products/:id/erase', to: 'products#erase', as: 'erase_product', via: [:delete]
      match '/products/:id/debug' => 'products#show_debug', as: 'product_debug', via: [:get, :put, :post]

      match 'products/:product_id/images/:id/mark_as_main', to: 'images#mark_as_main', as: 'mark_image_as_main', via: [:get, :put, :post]
      match 'products/:product_id/upload_images/:id', to: 'images#delete_image', as: 'product_delete_image', via: [:delete]
      match 'products/:product_id/upload_images', to: 'images#upload_images', as: 'product_upload_images', via: [:put, :post]
      match 'products_batch_update' => 'products#batch_update', as: 'batch_update_products', via: [:put, :post]


      ##
      # Seller
      match '/orders/:id/preview_invoice_email' => 'orders#preview_invoice_email', as:'order_preview_invoice_email', via: [:get]

      # Orders
      match '/orders/:id/update_messages' => 'orders#update_messages', via: [:put, :post], as: 'order_update_messages'
      match '/orders/:id' => 'orders#show', as:'order', via:[:get]
      match '/sales/:state' => 'orders#sales', as:'sales_in_state', via: [:get]
      match '/sales' => 'orders#sales', as:'sales', via: [:get]
      match '/msales' => 'orders#mobile_sales', as:'mobile_sales', via: [:get]

      # Store
      match '/payment_methods_and_retail_stores' => 'store_payment_methods#save_payment_methods_and_retail_stores', as:'payment_methods_and_retail_stores', via: [:get, :put, :post]
      match '/store_payment_methods/toggle' => 'store_payment_methods#toggle', as: 'toggle_store_payment_method', via: [:get, :put, :post]
      resources :store_payment_methods, only:[:index, :show, :update]
      get '/fill_your_shop' => 'stores#fill_your_shop', as: 'fill_your_shop'

      # Imports
      match '/scraper_page_imports/select(.:format)' => 'scraper_page_imports#select', as: 'select_scraper_page_imports', via: [:post, :put]
      match '/products/imported' => 'scraper_page_imports#products', as: 'imported_products', via: [:get]
      match 'scraper_page_imports' => 'scraper_page_imports#products', as: 'page_product_imports', via: [:get]

    end


    # Users
    get Spree.admin_path => 'admin/base#home', as: :admin_default

    get '/account' => 'users#account', as: 'account'
    match '/onboarding/:passcode/password' => 'users#onboarding_change_password', as: 'onboarding_change_password', via: [:get, :put, :post, :patch]
    get '/onboarding/:passcode' => 'users#onboarding', as: 'user_onboarding'

    get '/users/info' => 'admin/users#show', as: 'users_info'
    get '/users/:username' => 'home#not_found', as: 'users_detail'

    devise_scope :spree_user do
      match '/admin/sign_in_as/:id' => 'user_sessions#sign_in_as', as:'admin_sign_in_as', via: [:get, :put, :post]
    end

    ##
    # Products
    match '/products_s' => 'products#index', as: 's_products', via: [:get, :put, :post]
    match '/products_m' => 'products#index', as: 'm_products', via: [:get, :put, :post]
    match '/products_sd' => 'products#index', as: 'sd_products', via: [:get, :put, :post]
    match '/products_md' => 'products#index', as: 'md_products', via: [:get, :put, :post]
    match '/products_l' => 'products#index', as: 'l_products', via: [:get]
    match '/products_c' => 'products#index', as: 'c_products', via: [:get]
    match '/products/:id/exists_in_search' => 'products#exists_in_search', as: 'product_exists_in_search', via: [:get, :put, :post]
    match '/products/:id/related' => 'products#related_products', as: 'related_products', via: [:get, :put, :post]
    match '/related_option_types/:record_type/:record_id' => 'api/option_types#related', as: :related_option_types, via: [:get, :put, :post]
    match '/variants/:id/data' => 'products#variant_data', as: 'product_variant_data', via: [:get, :put, :post]
    match '/option_types/load' => 'api/option_types#load', as: :load_option_types, via: [:get, :put, :post]
    match '/admin/taxons/:id/related_option_types', to: 'admin/taxons#related_option_types', as: :taxon_related_option_types, via: [:get]

    #get '/search', to: 'products#index', as: 'search_by_id'
    #get '/search', to: 'searches#show', as: 'search_by_id'

    ##
    # Buyer
    match '/add_item_to_cart' => 'api/v2/storefront/cart#add_item', via: [:put, :post], as: 'populate_orders'
    match '/select_variant' => 'api/v2/storefront/cart#select_variant', via: [:put, :post], as: 'select_variant'
    match '/orders/:id/help' => 'orders#help', via: [:get], as: 'order_help'
    match '/orders/:id/upload_image' => 'orders#upload_image', via: [:patch, :put, :post], as: 'order_upload_image'
    match '/orders/:id/messages/:message_id' => 'orders#show_message', via: [:get], as: 'order_show_message'
    match '/orders/:id/messages' => 'orders#create_message', via: [:get, :put, :post], as: 'order_create_message'
    match '/orders' => 'orders#index', via: [:get], as: 'orders'
    patch "/orders/:id/update_channel", to: "orders#update_channel", as: :update_order_channel


    # Sellers
    get '/payment_methods_provided' => 'store_payment_methods#payment_methods_provided', as: 'payment_methods_provided'
    get '/payment_method_accounts' => 'store_payment_methods#accounts', as: 'payment_method_accounts'

    ##
    # Orders
    get '/recent_sales(.:format)' => 'orders#recent_sales',  as: 'recent_sales'

    # iOffer Landing
    match '/other' => 'home#other_site_accounts', via: [:get], as:'other'
    match '/contact_info' => 'home#payment_info', via: [:get], as: 'contact_info'
    match '/seller_contact_info' => 'home#payment_info', via: [:get], as: 'seller_contact_info'
    match '/payment_options' => 'home#payment_options', via: [:get], as: 'payment_options'
    match '/seller_obligations' => 'home#seller_obligations', via: [:get], as: 'seller_obligations'

    # iOffer Static Pages
    match '/privacy_policy' => 'base#privacy_policy', via: [:get], as:'privacy'
    match '/terms' => 'base#terms_of_use', via: [:get], as:'terms'

    get '/u/:code', to: 'item_reviews#show', as: :item_review
    get '/u/:code/purchases', to: 'item_reviews#purchases', as: :purchases_item_review


    # Must be here for spree home to access path urls
    namespace :ioffer, path: '/' do

      match '/seller_signup' => '/ioffer/users#new', via: [:get], as:'seller_signup'
      match '/payments' => '/ioffer/payment_methods#index', via: [:get], as: 'payments'
      match '/select_payment_methods' => '/ioffer/payment_methods#select_payment_methods', via: [:post, :put, :patch], as:'select_payment_methods'

      match '/save_contact_info' => '/ioffer/payment_methods#save_payment_info', via:[:put, :post], as: 'save_contact_info'

      match '/categories_brands' => '/ioffer/brands#index', via: [:get], as:'brands'
      match '/what_categories' => '/ioffer/brands#index', via: [:get], as:'what_categories'
      match '/select_brands' => '/ioffer/brands#select_brands', via: [:post, :put, :patch], as:'select_brands'
      match '/select_categories' => '/ioffer/categories#select_categories', via: [:post, :put, :patch], as:'select_categories'

      match '/email_subscriptions' => '/ioffer/email_subscriptions#create', via: [:post], as: 'email_subscriptions'
      match '/other_site_accounts' => '/ioffer/other_site_accounts#create', via: [:post]
    end
  end # add_routes

  ##
  # Messages

  namespace :user, path: '/' do
    match 'messages/list' => 'messages#index', via: [:get], as:'messages_list'
    resources :messages
    match 'messages/:id/image/:filename' => 'messages#image', via: [:get], as:'message_image'
    match 'messages/:id/thumb/:filename' => 'messages#thumb', via: [:get], as:'message_thumb'
  end

  ##
  # Search
  resources :search_keywords, only:[:index]

  # Retail
  namespace :retail, path: 'admin/retail' do
    resources :sites
    resources :site_categories, only: [:update, :show, :index]
  end

  # Scraper
  namespace :scraper, path:'admin/scraper' do
    match 'pages/preview(.:format)' => 'pages#preview', as: 'page_preview', via: [:get, :post, :put]
    match 'pages/:id/fetch(.:format)' => 'pages#fetch', as: 'page_fetch', via: [:get, :post, :put]
    match 'pages/:id/show_product(.:format)' => 'pages#show_product_from_saved_page', as:
    'page_show_product', via: [:get, :post, :put]

app/models/scraper/import_page_entry.rb
class Scraper::ImportPageEntry < ApplicationRecord
  self.table_name = 'scraper_import_runs_pages'

  belongs_to :import_run, class_name:'Scraper::ImportRun', foreign_key:'scraper_import_run_id'
  belongs_to :page, class_name:'Scraper::Page', foreign_key:'scraper_page_id'

  delegate :page_url, :page_type, :url_path, :url_params, :page_number, :pagination_number, :referrer_page_id, :root_referrer_page_id, to: :page

  def self.add_if_needed(url, import_run_attributes = {})
    uri = URI(url)
    scraper_page = ::Scraper::Page.add_if_needed(uri)
    page_entry = ::Scraper::ImportPageEntry.joins(:import_run).where(scraper_import_runs:{ retail_site_id: scraper_page.id } ).last
    if page_entry.nil?
      import_run = ::Scraper::ImportRun.create(
        retail_site_id: scraper_page.retail_site_id, 
        initiator_user_id: import_run_attributes[:initiator_user_id], 
        name: import_run_attributes[:name].present? ? import_run_attributes[:name] : "#{scraper_page.retail_site.name} Import on #{Time.now.to_s(:long)}",
        initial_url: url, keywords: import_run_attributes[:keywords], status: 'NEW' 
      )
      page_entry = ::Scraper::ImportPageEntry.create(scraper_import_run_id: import_run.id, scraper_page_id: scraper_page.id )
    end
    page_entry
  end

  # alias_method just cannot work
  def import_page_id
    scraper_import_run_id
  end
end

app/controllers/scraper/page_product_import.rb
class Scraper::PageProductImport < ::ApplicationRecord
  self.table_name = 'scraper_page_product_imports'

  belongs_to :import_run, class_name:'Scraper::ImportRun', foreign_key:'scraper_import_run_id'
  belongs_to :page, class_name:'Scraper::Page', foreign_key:'scraper_page_id'

  belongs_to :product, -> { with_deleted }, class_name:'Spree::Product', foreign_key:'spree_product_id'
end

app/controllers/scraper/pages_controller.rb
class Scraper::PagesController < ApplicationController

  inherit_resources

  layout 'spree/layouts/admin'

  helper ::Retail::SitesHelper

  before_action :populate_search, only: [:index]
  before_action :authorize_admin, only: [:create]

  def show
    @page_title = "Page (#{params[:id]})"
    super
  end

  def show_product_from_saved_page
    @product = resource.retail_product
    unless @product
      agent = resource.retail_site.scraper
      mechanize_page = resource.make_mechanize_page(agent, params[:locale])
      @product = resource.make_product_from_page(mechanize_page, false)
    end
    logger.info "product: #{@product}"
    respond_to do|format|
      format.js
    end
  end

  ##
  # Fetch page
  def update
    params.permit(:scraper_page, :reparse, :update_product_card, :scraper_page_ids)
    logger.info "| update page #{resource.id}, reparse? #{params[:reparse]}"
    if params[:reparse]
      resource.fetch!
    else
      resource.fetch_if_needed
    end
  rescue Exception => e
    logger.warn e.message
    logger.warn e.backtrace.join("\n  ")
    @exception = e
  ensure
    respond_to do|format|
      format.js
    end
  end

  ##
  # Simply calls Scraper::Page#fetch!, either creating product or adding more pages.
  # Different from #update which saves source in file first and uses Ruby-based 
  # scraper to parse the page source.
  def fetch
    result = resource.fetch!
    logger.info "** result: #{result}"
    if resource.page_type == 'detail'
      @spree_product = result
      if @spree_product
        import_run = resource.create_import_run_if_needed!
        import = ::Spree::ScraperPageImport.find_or_initialize_by(scraper_page_id: resource.id, spree_product_id: @spree_product.id)
        import.scraper_import_run_id ||= import_run.id
        import.save
      end
    else
      @scraper_pages = result
    end
  rescue Exception => action_e
    logger.warn "** Error fetching page(#{resource.try(:id)}: #{action_e}\n#{action_e.backtrace}"
    @error = action_e
  end

  def source_file
    @source = ''
    if resource.file_path.blank?
      @source = '<h3> No file saved for this page</h3>'
    elsif !File.exists?(resource.file_path)
      @source = "<h3>File not found #{resource.file_path}</h3>"
    else
      @source = File.open(resource.file_path).read
    end
  end

  def destroy
    last_run = resource.import_runs.try(:last)
    super do|format|
      format.html { redirect_to scraper_pages_path }
      format.js
    end
  end

  def preview
    params.permit(:source, :name, :retail_site_id)
    @page = Scraper::Page.new(retail_site_id: params[:retail_site_id], page_type:'detail')
    if params[:source].present?
      @source = params[:source]
      @retail_site = if params[:retail_site_id].to_i > 0
          Retail::Site.find_by_id(params[:retail_site_id])
        else
          Retail::Site.where(name: params[:name] || 'ioffer').first
        end
      @page.retail_site = @retail_site  
      if @retail_site  
        @mechanize_page = Mechanize::Page.new( URI('/admin/pages/source'), nil, params[:source], 200, @retail_site.scraper)
        @product = @page.make_product_from_page(@mechanize_page)
      end
    end
  end

  protected

  def populate_search
    params[:q] ||= {}
    [:retail_site_id, :url_path].each do|pname|
      params[:q]["#{pname}_eq".to_sym] = params[pname] if params[pname]
    end
    if params[:url].present?
      @uri = URI( params[:url] )
      @retail_site = params[:q][:retail_site_id_eq] ?
        ::Retail::Site.find(params[:q][:retail_site_id_eq]) : ::Retail::Site.find_matching_site(params[:url] )
    end
    unless @pages && @search
      @search = ::Scraper::Page.ransack(params[:q])
      @pages = @search.result.includes(:retail_site, :scraper_page_imports).page(params[:page] ).per(50).order('id desc')
      if params[:url].present?
        @uri = URI( params[:url] )
        @retail_site = params[:retail_site_id] ?
          ::Retail::Site.find(params[:retail_site_id]) : ::Retail::Site.find_matching_site(params[:url] )
        @pages = @pages.where(retail_site_id: @retail_site.id) if @retail_site
        @pages = @pages.where(url_path: @uri.path )
      end
    end
    if @pages.count == 1
      return redirect_to( scraper_page_path(@pages.first) )
    else
      logger.info "| no of pages #{@pages.count}"
    end

    if params[:scraper_page]
      [:page_type].each do|a|
        @pages = @pages.where(a => params[:scraper_page][a] )
      end
    end
  end

  def collection
    super.includes(:retail_site, :scraper_page_imports)
  end

  private

  def page_params
    params.permit(:scraper_page, :reparse, :update_product_card)
    params.require(:scraper_page).permit(:page_type, :retail_site_id, :retail_store_id, :title, :page_url, :page_number,
                                 :referrer_page_id, :root_referrer_page_id, :file_path, :file_status)
  end

end

app/helpers/scraper/pages_helper.rb
module Scraper::PagesHelper

  PAGE_TYPE_TO_GLYPHICON_SUBCLASS = {
    'landing' => 'home', 'index' => 'list', 'store' => 'shopping-cart', 'detail' => 'modal-window'
  }

  # Font-awesome icon CSS class
  def page_type_icon_css_class(page_type)
    'glyphicon glyphicon-' + PAGE_TYPE_TO_GLYPHICON_SUBCLASS[page_type].to_s
  end

  def previous_page_of(current_page)
    current_page.retail_site.pages.where('id < ?', current_page.id).order('id desc').limit(1).first
  end

  def next_page_of(current_page)
    current_page.retail_site.pages.where('id > ?', current_page.id).order('id asc').limit(1).first
  end

  ##
  # Strip away html, body tags, and script section
  def strip_page_source(source)
    s = source.clone
    s.gsub! /(<\/?html>)/, ''
    s.gsub! /(<\/?body>)/, ''
    s.gsub! /(<script[^>]*>.*<\/script>)/, ''
    s
  end

  def shortened_ending_path(path)
    parts = path.split('/')
    parts[parts.size - 3, parts.size].join('/')
  end
end

app/views/scraper/pages/_fetch_table_row.html.haml
:ruby
  # Require locals:
  #   page [Scraper::Page]
  #   or import_page_entry [Scraper::ImportPageEntry]
  # Optional locals:
  #   extra_link_options [Hash of parameters]
  page = nil if not defined?(page)
  import_page_entry = nil if not defined?(import_page_entry)
  page = import_page_entry.page if defined?(import_page_entry) && import_page_entry && page.nil?
  extra_link_options = {} if not defined?(extra_link_options)
  extra_link_options ||= {}
  extra_link_options.merge!(return_url: request.path + "?t=#{Time.now.to_i}") if page.page_type == 'index'
%tr(id="page_row_#{page.id}" data-page-id="#{page.id}" data-page-type="#{page.page_type}" data-file-status="#{page.file_status}")
  %td
    %i(class="#{page_type_icon_css_class(page.page_type) }" title="Page type: #{page.page_type}")
    &nbsp;
    =link_to page.id, scraper_page_path(page), title:"Created#{" page entry #{import_page_entry.id}" if import_page_entry} at #{page.created_at.to_s(:db)}", 'data-toggle'=>'tooltip'
  %td
    - if page.retail_site
      %strong= link_to(page.retail_site&.name, scraper_pages_path(q:{ retail_site_id_eq: page.retail_site_id }) )
    = link_to page.relative_page_url.truncate(60), page.abs_page_url, target:'_blank', title: page.relative_page_url, 'data-toggle'=>'tooltip'
  %td
    %span(title="#{page.file_path}")=page.file_status
  %td(id="page_row_status_#{page.id}" class="text-right")
    - if page.page_type == 'detail' && page.scraper_page_imports.all.size > 0
      - page.scraper_page_imports.each do|scraper_page_import|
        = link_to(scraper_page_import.spree_product_id, spree.product_path(id: scraper_page_import.spree_product_id), method:'get', 'data-toggle'=>'tooltip', title:'Product from parsing', target:'_blank') 
    - elsif !page.completed?
      = link_to('Fetch', scraper_page_fetch_path( (extra_link_options || {}).merge(id: page.id) ), remote: true, 'data-disable-with'=>'Fetching ..', class:'btn btn-info', name:"fetch_#{page.page_type}_button" )
    &nbsp;&nbsp;
    = link_to(scraper_page_path(page), method:'delete', remote: true, data:{confirm:"Are you sure to delete this page?"}, title:'Delete this page') do
      %i.btn.btn-danger.glyphicon.glyphicon-remove 
    - if @error
      .error-tip.dark-shadow 
        = @error

app/views/scraper/pages/_table_row.html.haml
:ruby
  # Required locals:
  #   page [Scraper::Page]
%tr(id="page_row_#{page.id}" data-page-id="#{page.id}" data-file-status="#{page.file_status}")
  %td.text-sm=link_to page.id, scraper_page_path(page)
  %td
    %i(class="#{page_type_icon_css_class(page.page_type) }" title="Page type: #{page.page_type}")
    &nbsp;
    = link_to page.relative_page_url.truncate(60), scraper_page_path(page), target:'_blank', title:'More detail of the page'
    &nbsp;&nbsp;
    = link_to page.abs_page_url, target:'_blank', 'data-toggle'=>'tooltip', title:'Visit this page' do
      %i.fas.fa-external-link-alt 
  %td
    - if page.imported_spree_product_ids.present?
      %p.text-sm
        - page.imported_spree_product_ids.each_with_index do|product_id, pindex|
          = ', ' if pindex >= 1
          = link_to(product_id.to_s, spree.product_path(id: product_id), target:'_blank', title:'Click to View Product')
    - if page.file_status =~ /\Acancell?ed\Z/i
      %i.fa.fa-times.text-danger(title='Cancelled') 
    - elsif page.file_path.present?
      = link_to(scraper_page_show_product_path(id: page.id), remote:true, method:'get', 'data-toggle'=>'tooltip', title:'Product from parsing') do
        %i.fa.fa-check
    - else
      = link_to(scraper_page_path(page), remote:true, method:'put', title:'Fetch the page') do
        %i.fa.fa-download.text-info

app/views/scraper/pages/index.html.haml
:ruby
  retail_site_options = Retail::Site.all.collect{|site| [site.name, site.id] }
  # options_from_collection_for_select(Retail::Site.all, 'id', 'name')
- content_for :head do
  = stylesheet_link_tag 'spree/scraper'
.container
  .float-right
    %button(type='button' data-toggle="modal" data-target="#page_preview_modal") Preview
  .clearfix
  %h4 Scraper Pages

  .search-form.m-3
    = search_form_for @search do |f|
      .row
        .col-4
          = f.label(:retail_site_id_eq) { 'Site' }
          = f.select :retail_site_id_eq, [['- All - ', nil] ] + retail_site_options
        .col-4
          = f.label(:file_status_eq) { 'Status'}
          = f.select :file_status_eq, [['- Any -', nil]] + Scraper::Page::FILE_STATUSES
        .col-4
          = f.submit { 'Search' }

  - if collection.blank?
    %h4 No pages found.
    - if params[:url].present?
      %h4 Want to add this page?
  - else
    %table.table.table-striped
      %thead
        %tr
          %th ID
          %th Type & Path
          %th Status
          %th Actions
      %tbody
        = render partial:'scraper/pages/fetch_table_row', collection: collection, as: :page
    - if collection.respond_to?(:total_pages)
      %div(class="row pl-md-4 pl-sm-4")
        .col-md-3.col-sm-2
        .col-md-6.col-sm-8
          %div(class="plp-pagination d-none d-lg-flex")
            = paginate collection, window: 2, theme: 'twitter-bootstrap-4'
          %div(class="plp-pagination d-lg-none")
            = paginate collection, window: 1, theme: 'twitter-bootstrap-4'
    %br/
    %br/

%div(class="modal fade" id="page_preview_modal" style="max-width:100%; margin:auto;" tabindex="-1" role="dialog" aria-labelledby="page_preview_modal_label" aria-hidden="true")
  .modal-dialog(role="document" style="max-width:70%;")
    = form_tag(scraper_page_preview_path) do
      .modal-content
        .modal-header
          %h5(class="modal-title" id="page_preview_modal_label")
          %button(type="button" class="close" data-dismiss="modal" aria-label="Close")
            %span(aria-hidden="true") &times;
        .modal-body
          %label(for='retail_site_id') Site
          = select_tag(:retail_site_id, options_for_select(retail_site_options) )
          %br/
          %label(for='source') Page Source Code
          %br/
          = text_area_tag(:source, @source, style:'width: 100%; height: 30rem;')
        .modal-footer
          %button(type="button" class="" data-dismiss="modal") Cancel
          %button(type="submit" class="") Preview

app/views/scraper/pages/source_file.html.haml
:ruby
  admin_breadcrumb link_to(resource.retail_site.domain, resource.retail_site)
  admin_breadcrumb link_to('< Back to Page', resource)
  
.row
  %nav(aria-label="breadcrumb")
    %ol.breadcrumb.admins-breadcrumb
      %li.breadcrumb-item
        Site:
        = link_to resource.retail_site.domain, retail_site_path(resource.retail_site)
      %li.breadcrumb-item
        = link_to resource.relative_page_url.gsub(/\A(\/)/,''), resource.retail_site.abs_url(resource.page_url), target:'_blank'

%nav
  %ul(class="tabs justify-content-center")
    %li(class="#{params[:source_format] == 'html' ? ' active' : ''}")
      = link_to 'HTML', resource.page_file_relative_url || page_source_file_path(id: resource.id, source_format: 'html')
    %li(class="#{params[:source_format] != 'html' ? ' active' : ''}")
      = link_to 'Raw', scraper_page_source_file_path(id: resource.id, source_format: 'raw')
- if params[:source_format].blank? || params[:source_format] == 'raw'
  %code
    = @source
- elsif resource.page_file_relative_url.present?
  .row
    .col-12
      %iframe(id="scraper_page_iframe" style="width:95%; height:600px;" src="#{resource.page_file_relative_url}")
- else
  = strip_page_source( @source ).html_safe

app/views/scraper/pages/update.js.erb
var col = $("#page_row_<%= resource.id -%> td:last-child");
$("#page_row_<%= resource.id -%>").attr('data-file-status', '<%= resource.file_status -%>');
<%
if resource.file_path.present? -%>
	col.html("<%= escape_javascript(link_to(' ', scraper_page_show_product_path(id: resource.id), remote:true, method:'get', class:'fa fa-check', 'data-toggle'=>'tooltip', title:'Product from parsing') ) -%>");
<% elsif resource.file_status == 'PAGE_NOT_FOUND' -%>
	col.html("<i class='fa fa-times'/>");
	window.setTimeout(function(){ $("#page_row_<%= resource.id -%>").fadeOut(); }, 1500 );
<%
 else -%>
	col.html("<%= escape_javascript(link_to(' ', scraper_page_path(resource), remote:true, method:'put', title:'Fetch the page', class:'fa fa-download text-info').html_safe ) -%>");
<% end -%>
<% 
if params[:update_product_container].present?
	if resource.spree_products.present? -%>
		$("<%= params[:update_product_container] %>").html("<div class='d-flex justify-content-center' style='margin: 0; background-color:#eeeeee; height:50%; padding: 10%;'><div class='spinner-border' role='status'><span class='sr-only'>Reparsing ...</span></div></div>");
		<%
		resource.spree_products.each do|product| -%>
			$("<%= params[:update_product_container] %>").append("<%= escape_javascript(render(partial:'retail/products/card', locals:{ product: product } )) %>");
<%
		end # resource.spree_products.each 
	elsif @exception -%>
		alert("Error: <%= @exception.message -%> ");
		$("<%= params[:update_product_container] %>").html("<div class='d-flex justify-content-center' style='margin: 0; background-color:#eeeeee; height:50%; padding: 10%;'><div class='spinner-border' role='status'><span class='sr-only'>Reparsing ...</span></div></div>");
		$("<%= params[:update_product_container] %>").html("<code><%= @exception.message -%></code>");
<% end -%>
<% end # update_product_container -%>
<% if params[:update_links_container].present? -%>
	$("<%= params[:update_links_container] %>").html("<%= escape_javascript(render(partial:'scraper/pages/links_from_mechanize_page', locals:{ scraper: resource.scraper, mechanize_page: resource.make_mechanize_page } )) %>");
<% end -%>